import { createServerOnlyFn } from "@tanstack/react-start";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { betterAuth } from "better-auth/minimal";
import {
  admin,
  magicLink,
  twoFactor,
  organization,
} from "better-auth/plugins";
import { passkey } from "@better-auth/passkey";
import { tanstackStartCookies } from "better-auth/tanstack-start";
import { eq } from "drizzle-orm";
import { ROLES, ROUTES } from "@/constants";
import { env } from "@/env/server";
import { db } from "@/lib/db";
import { user as userTable } from "@/lib/db/schema";
import {
  sendUserEmailVerifiedEvent,
  sendUserSignedUpEvent,
} from "@/lib/inngest/events";
import { sendEmail } from "../email";
import { ac, roles } from "./permissions";
import { getBillingPlugin, logBillingConfig } from "@/lib/billing";

// Log billing configuration on startup
logBillingConfig();

/**
 * Ensure URLs generated by Better Auth work when the app is hosted behind a base path (e.g. /blog)
 * and accessed via Traefik/Tailscale.
 */
function withPublicBaseUrl(inputUrl: string): string {
  try {
    const base = new URL(env.VITE_BASE_URL);
    const u = new URL(inputUrl);

    // force origin to our public base
    u.protocol = base.protocol;
    u.username = base.username;
    u.password = base.password;
    u.host = base.host;

    // prefix path with base pathname (e.g. /blog)
    const basePath = base.pathname.replace(/\/$/, "");
    if (basePath && !u.pathname.startsWith(basePath + "/") && u.pathname !== basePath) {
      u.pathname = `${basePath}${u.pathname.startsWith("/") ? "" : "/"}${u.pathname}`;
    }

    // Better Auth sometimes includes callbackURL as a root-relative path (e.g. /auth/reset-password).
    // If we're hosted under a base path, that would drop the prefix.
    const callbackURL = u.searchParams.get("callbackURL");
    if (callbackURL && basePath && callbackURL.startsWith("/") && !callbackURL.startsWith(basePath + "/")) {
      u.searchParams.set("callbackURL", `${basePath}${callbackURL}`);
    }

    return u.toString();
  } catch {
    return inputUrl;
  }
}

const getAuthConfig = createServerOnlyFn(() =>
  betterAuth({
    baseURL: `${env.VITE_BASE_URL}/api/auth`,
    telemetry: {
      enabled: false,
    },
    database: drizzleAdapter(db, {
      provider: "pg",
    }),

    plugins: [
      magicLink({
        async sendMagicLink({ email, url }) {
          const existing = await db.query.user.findFirst({
            where: (u, { eq }) => eq(u.email, email),
            columns: { id: true },
          });

          // Ensure the link uses the public base URL and preserves the app base path.
          // Also fixes callbackURL paths (e.g. /dashboard -> /blog/dashboard)
          const magicLinkUrl = withPublicBaseUrl(url);

          const res = await sendEmail({
            to: email,
            subject: "Your sign-in link",
            template: "magic-link",
            data: { magicLinkUrl },
            userId: existing?.id,
            context: "auth",
            eventProperties: { kind: "magic-link" },
          });

          // Critical: if SMTP fails, Better Auth would still treat this as "sent" unless we throw.
          // Throwing here surfaces the error to the client so users don't get stuck waiting for an email.
          if (!res.success) {
            throw new Error(res.error || "Failed to send magic link email");
          }
        },
      }),
      ...(env.ENABLE_PASSKEYS ? [passkey()] : []),
      ...(env.ENABLE_2FA ? [twoFactor({
        otpOptions: {
          digitsOnly: true,
          validForMinutes: 2,
          length: 6,
          sendOTP: async ({ user, otp }) => {
            const res = await sendEmail({
              to: user.email,
              subject: "Your Verification Code",
              template: "otp-verification",
              data: {
                userName: user.name || "there",
                otp,
              },
              userId: user.id,
              context: "session",
              // context: "auth",
              eventProperties: { kind: "two-factor-otp" },
            });
            if (!res.success) {
              throw new Error(res.error || "Failed to send OTP email");
            }
          },
        },
      })] : []),
      admin({
        ac,
        roles: {
          user: roles.user,
          author: roles.author,
          moderator: roles.moderator,
          admin: roles.admin,
          superAdmin: roles.superAdmin,
        },
        defaultRole: ROLES.USER,
        impersonation: {
          enabled: true,
          allowImpersonatingAdmins: true, // Superadmins can impersonate admins
          impersonationSessionDuration: 60 * 60, // 1 hour
        },
      }),
      organization({
        async sendInvitationEmail(data) {
          try {
            await sendEmail({
              to: data.email,
              subject: `Invitation to join ${data.organization.name}`,
              template: "organization-invitation",
              data: {
                organizationName: data.organization.name,
                inviterName: data.inviter.user.name,
                inviterEmail: data.inviter.user.email,
                invitationUrl: withPublicBaseUrl(
                  `${env.VITE_BASE_URL}${ROUTES.AUTH.CALLBACK.ACCEPT_INVITATION}?invitationId=${encodeURIComponent(data.invitation.id)}&redirectTo=${encodeURIComponent(ROUTES.ACCOUNT.ORGANIZATIONS)}`,
                )
              },
              userId: data.inviter.user.id,
              context: "organization",
              eventProperties: {
                kind: "invitation",
                organizationId: data.organization.id,
              },
            });

          } catch (error) {
            console.error("Failed to send organization invitation email:", error);
            throw error;
          }
        },
      }),
      tanstackStartCookies(),
      // Billing plugin (Stripe or Polar based on BILLING_PROVIDER env)
      ...(getBillingPlugin() ? [getBillingPlugin()!] : []),
    ],

    user: {
      changeEmail: { enabled: true },
      deleteUser: { enabled: true },
    },

    session: {
      cookieCache: {
        enabled: true,
        maxAge: 5 * 60, // 5 minutes
      },
      expiresIn: 60 * 60 * 24 * 7, // 7 days
      updateAge: 60 * 60 * 24, // 1 day
    },

    socialProviders: {
      google: {
        clientId: env.GOOGLE_CLIENT_ID!,
        clientSecret: env.GOOGLE_CLIENT_SECRET!,
      },
    },

    emailAndPassword: {
      enabled: true,
      requireEmailVerification: true,
      minPasswordLength: 8,
      sendResetPassword: async ({ user, url }) => {
        const resetUrl = withPublicBaseUrl(url);

        const res = await sendEmail({
          to: user.email,
          subject: "Reset Your Password",
          template: "password-reset",
          data: {
            userName: user.name || "there",
            resetUrl,
          },
          userId: user.id,
          context: "auth",
          eventProperties: { kind: "password-reset" },
        });
        if (!res.success) {
          throw new Error(res.error || "Failed to send password reset email");
        }
      },
      onPasswordReset: async ({ user }) => {
        // If the user successfully reset their password via the email link/token,
        // they have proven access to the mailbox, so we can treat it as verified.
        if (!user.emailVerified) {
          await db
            .update(userTable)
            .set({ emailVerified: true })
            .where(eq(userTable.id, user.id));
        }
      },
    },

    emailVerification: {
      sendOnSignUp: true,
      autoSignInAfterVerification: false,
      sendVerificationEmail: async ({ user, url, token }) => {
        const verificationToken =
          token || new URL(url).searchParams.get("token") || "";
        if (!verificationToken) {
          throw new Error("Verification token missing");
        }

        const verificationUrl = `${env.VITE_BASE_URL}/auth/callback/verify-email?token=${encodeURIComponent(verificationToken)}`;
        // Defensive: ensure base-path correctness if env.VITE_BASE_URL is missing the base-path suffix
        const fixedVerificationUrl = withPublicBaseUrl(verificationUrl);

        const res = await sendEmail({
          to: user.email,
          subject: "Verify Your Email Address",
          template: "email-verification",
          data: {
            userName: user.name || "there",
            verificationUrl: fixedVerificationUrl,
          },
          userId: user.id,
          context: "auth",
          eventProperties: { kind: "email-verification" },
        });
        if (!res.success) {
          throw new Error(res.error || "Failed to send verification email");
        }

        // Best-effort: treat "send verification on sign up" as the "signed up" event.
        // Guard against firing on email-change verification by checking how recent the account is.
        const createdAtMs = (() => {
          try {
            // Better Auth returns Date-ish values; normalize defensively
            return new Date((user as any).createdAt ?? 0).getTime();
          } catch {
            return 0;
          }
        })();
        const tenMinutesMs = 10 * 60 * 1000;
        if (createdAtMs > 0 && Date.now() - createdAtMs < tenMinutesMs) {
          await sendUserSignedUpEvent({
            userId: user.id,
            email: user.email,
            name: user.name ?? undefined,
          }).catch((err) =>
            console.error("Failed to send user signed up event:", err),
          );
        }
      },
      afterEmailVerification: async (updatedUser) => {
        await sendUserEmailVerifiedEvent({
          userId: updatedUser.id,
          email: updatedUser.email,
        }).catch((err) =>
          console.error("Failed to send user email verified event:", err),
        );
      },
    },

    account: {
      accountLinking: {
        enabled: true,
        allowDifferentEmails: true,
        updateUserInfoOnLink: true,
        allowUnlinkingAll: true,
        trustedProviders: ["google"],
      },
    },

    rateLimit: {
      window: 60, // 1 minute
      max: 100, // 100 requests per minute
    },

    advanced: {
      useSecureCookies: env.NODE_ENV === "production",
      cookiePrefix: `${env.COOKIE_PREFIX}`,
      crossSubDomainCookies: {
        enabled: false,
      },
      defaultCookieAttributes: {
        sameSite: "lax",
        path: "/",
        httpOnly: true,
      },
    },

    experimental: {
      // https://www.better-auth.com/docs/adapters/drizzle#joins-experimental
      joins: true,
    },
  }),
);

export const auth = getAuthConfig();
