/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteRouteImport } from './routes/terms/route'
import { Route as PrivacyRouteRouteImport } from './routes/privacy/route'
import { Route as CookiesRouteRouteImport } from './routes/cookies/route'
import { Route as blogRouteRouteImport } from './routes/(blog)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as blogIndexRouteImport } from './routes/(blog)/index'
import { Route as NewsletterConfirmRouteImport } from './routes/newsletter/confirm'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as blogTopicsRouteImport } from './routes/(blog)/topics'
import { Route as blogSearchRouteImport } from './routes/(blog)/search'
import { Route as blogAuthorsRouteImport } from './routes/(blog)/authors'
import { Route as blogAuthorOnboardingRouteImport } from './routes/(blog)/author-onboarding'
import { Route as blogAboutRouteImport } from './routes/(blog)/about'
import { Route as blogSlugRouteImport } from './routes/(blog)/$slug'
import { Route as authPagesSignupRouteImport } from './routes/(auth-pages)/signup'
import { Route as authPagesLogoutRouteImport } from './routes/(auth-pages)/logout'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as authenticatedEditorRouteRouteImport } from './routes/(authenticated)/editor/route'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as authenticatedBillingRouteRouteImport } from './routes/(authenticated)/billing/route'
import { Route as authenticatedAdminRouteRouteImport } from './routes/(authenticated)/admin/route'
import { Route as authenticatedAccountRouteRouteImport } from './routes/(authenticated)/account/route'
import { Route as blogAtusernameIndexRouteImport } from './routes/(blog)/@$username/index'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as authenticatedBillingIndexRouteImport } from './routes/(authenticated)/billing/index'
import { Route as authenticatedAdminIndexRouteImport } from './routes/(authenticated)/admin/index'
import { Route as authenticatedAccountIndexRouteImport } from './routes/(authenticated)/account/index'
import { Route as authPagesAuthIndexRouteImport } from './routes/(auth-pages)/auth/index'
import { Route as ApiV1TagsRouteImport } from './routes/api/v1/tags'
import { Route as ApiV1PostsRouteImport } from './routes/api/v1/posts'
import { Route as ApiV1CategoriesRouteImport } from './routes/api/v1/categories'
import { Route as ApiV1AuthorsRouteImport } from './routes/api/v1/authors'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiInngestInngestRouteImport } from './routes/api/inngest/inngest'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedOrgOrganizationViewRouteImport } from './routes/(authenticated)/org/$organizationView'
import { Route as authenticatedErrorsErrorRouteImport } from './routes/(authenticated)/errors/$error'
import { Route as authenticatedEditorNewRouteImport } from './routes/(authenticated)/editor/new'
import { Route as authenticatedDashboardBecomeAuthorRouteImport } from './routes/(authenticated)/dashboard/become-author'
import { Route as authenticatedDashboardAssetsRouteImport } from './routes/(authenticated)/dashboard/assets'
import { Route as authenticatedBillingSuccessRouteImport } from './routes/(authenticated)/billing/success'
import { Route as authenticatedBillingCancelRouteImport } from './routes/(authenticated)/billing/cancel'
import { Route as authenticatedAdminUsersRouteImport } from './routes/(authenticated)/admin/users'
import { Route as authenticatedAdminStorageRouteImport } from './routes/(authenticated)/admin/storage'
import { Route as authenticatedAdminRbacRouteImport } from './routes/(authenticated)/admin/rbac'
import { Route as authenticatedAccountAccountViewRouteImport } from './routes/(authenticated)/account/$accountView'
import { Route as authPagesAuthAuthViewRouteImport } from './routes/(auth-pages)/auth/$authView'
import { Route as authenticatedAdminBillingRouteRouteImport } from './routes/(authenticated)/admin/billing/route'
import { Route as authenticatedAdminBlogIndexRouteImport } from './routes/(authenticated)/admin/blog/index'
import { Route as authenticatedAdminBillingIndexRouteImport } from './routes/(authenticated)/admin/billing/index'
import { Route as authenticatedAdminApiIndexRouteImport } from './routes/(authenticated)/admin/api/index'
import { Route as ApiV1PostsSlugRouteImport } from './routes/api/v1/posts/$slug'
import { Route as ApiStorageFilesSplatRouteImport } from './routes/api/storage/files/$'
import { Route as ApiStorageAvatarUserIdRouteImport } from './routes/api/storage/avatar/$userId'
import { Route as ApiAuthPasskeyVerifyRegistrationRouteImport } from './routes/api/auth/passkey/verify-registration'
import { Route as ApiAuthPasskeySignInRouteImport } from './routes/api/auth/passkey/sign-in'
import { Route as ApiAuthPasskeyRegistrationOptionsRouteImport } from './routes/api/auth/passkey/registration-options'
import { Route as ApiAuthPasskeyAddPasskeyRouteImport } from './routes/api/auth/passkey/add-passkey'
import { Route as blogSitesSiteSlugPageSlugRouteImport } from './routes/(blog)/sites/$siteSlug/$pageSlug'
import { Route as authenticatedOrgSlugOrganizationViewRouteImport } from './routes/(authenticated)/org/$slug/$organizationView'
import { Route as authenticatedAdminOrganizationOrganizationViewRouteImport } from './routes/(authenticated)/admin/organization/$organizationView'
import { Route as authenticatedAdminBlogTagsRouteImport } from './routes/(authenticated)/admin/blog/tags'
import { Route as authenticatedAdminBlogSitesRouteImport } from './routes/(authenticated)/admin/blog/sites'
import { Route as authenticatedAdminBlogNewsletterRouteImport } from './routes/(authenticated)/admin/blog/newsletter'
import { Route as authenticatedAdminBlogMediaRouteImport } from './routes/(authenticated)/admin/blog/media'
import { Route as authenticatedAdminBlogCommentsRouteImport } from './routes/(authenticated)/admin/blog/comments'
import { Route as authenticatedAdminBlogCategoriesRouteImport } from './routes/(authenticated)/admin/blog/categories'
import { Route as authenticatedAdminBlogAuthorsRouteImport } from './routes/(authenticated)/admin/blog/authors'
import { Route as authenticatedAdminBlogAnalyticsRouteImport } from './routes/(authenticated)/admin/blog/analytics'
import { Route as authenticatedAdminBillingSubscriptionsRouteImport } from './routes/(authenticated)/admin/billing/subscriptions'
import { Route as authenticatedAdminBillingCustomersRouteImport } from './routes/(authenticated)/admin/billing/customers'
import { Route as authenticatedAdminBillingCreditsRouteImport } from './routes/(authenticated)/admin/billing/credits'
import { Route as authenticatedAdminApiNewRouteImport } from './routes/(authenticated)/admin/api/new'
import { Route as authenticatedAdminApiKeyIdRouteImport } from './routes/(authenticated)/admin/api/$keyId'
import { Route as authenticatedAccountOrganizationsOrganizationViewRouteImport } from './routes/(authenticated)/account/organizations/$organizationView'
import { Route as authenticatedAccountOrganizationOrganizationViewRouteImport } from './routes/(authenticated)/account/organization/$organizationView'
import { Route as authPagesAuthCallbackVerifyEmailRouteImport } from './routes/(auth-pages)/auth/callback/verify-email'
import { Route as authPagesAuthCallbackAcceptInvitationRouteImport } from './routes/(auth-pages)/auth/callback/accept-invitation'
import { Route as authenticatedAdminBlogPostsIndexRouteImport } from './routes/(authenticated)/admin/blog/posts/index'
import { Route as authenticatedAdminBlogPostsNewRouteImport } from './routes/(authenticated)/admin/blog/posts/new'
import { Route as authenticatedAccountOrganizationsSlugOrganizationViewRouteImport } from './routes/(authenticated)/account/organizations/$slug/$organizationView'
import { Route as authenticatedAccountOrganizationSlugOrganizationViewRouteImport } from './routes/(authenticated)/account/organization/$slug/$organizationView'
import { Route as authenticatedAdminBlogPostsPostIdEditRouteImport } from './routes/(authenticated)/admin/blog/posts/$postId.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRouteRoute = TermsRouteRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRouteRoute = PrivacyRouteRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRouteRoute = CookiesRouteRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const blogRouteRoute = blogRouteRouteImport.update({
  id: '/(blog)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const blogIndexRoute = blogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => blogRouteRoute,
} as any)
const NewsletterConfirmRoute = NewsletterConfirmRouteImport.update({
  id: '/newsletter/confirm',
  path: '/newsletter/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const blogTopicsRoute = blogTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => blogRouteRoute,
} as any)
const blogSearchRoute = blogSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => blogRouteRoute,
} as any)
const blogAuthorsRoute = blogAuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => blogRouteRoute,
} as any)
const blogAuthorOnboardingRoute = blogAuthorOnboardingRouteImport.update({
  id: '/author-onboarding',
  path: '/author-onboarding',
  getParentRoute: () => blogRouteRoute,
} as any)
const blogAboutRoute = blogAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => blogRouteRoute,
} as any)
const blogSlugRoute = blogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => blogRouteRoute,
} as any)
const authPagesSignupRoute = authPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLogoutRoute = authPagesLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authenticatedEditorRouteRoute =
  authenticatedEditorRouteRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedBillingRouteRoute =
  authenticatedBillingRouteRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdminRouteRoute = authenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedAccountRouteRoute =
  authenticatedAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const blogAtusernameIndexRoute = blogAtusernameIndexRouteImport.update({
  id: '/@$username/',
  path: '/@$username/',
  getParentRoute: () => blogRouteRoute,
} as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedBillingIndexRoute =
  authenticatedBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedBillingRouteRoute,
  } as any)
const authenticatedAdminIndexRoute = authenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedAdminRouteRoute,
} as any)
const authenticatedAccountIndexRoute =
  authenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedAccountRouteRoute,
  } as any)
const authPagesAuthIndexRoute = authPagesAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const ApiV1TagsRoute = ApiV1TagsRouteImport.update({
  id: '/api/v1/tags',
  path: '/api/v1/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostsRoute = ApiV1PostsRouteImport.update({
  id: '/api/v1/posts',
  path: '/api/v1/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CategoriesRoute = ApiV1CategoriesRouteImport.update({
  id: '/api/v1/categories',
  path: '/api/v1/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthorsRoute = ApiV1AuthorsRouteImport.update({
  id: '/api/v1/authors',
  path: '/api/v1/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestInngestRoute = ApiInngestInngestRouteImport.update({
  id: '/api/inngest/inngest',
  path: '/api/inngest/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedOrgOrganizationViewRoute =
  authenticatedOrgOrganizationViewRouteImport.update({
    id: '/org/$organizationView',
    path: '/org/$organizationView',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedErrorsErrorRoute =
  authenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedEditorNewRoute = authenticatedEditorNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => authenticatedEditorRouteRoute,
} as any)
const authenticatedDashboardBecomeAuthorRoute =
  authenticatedDashboardBecomeAuthorRouteImport.update({
    id: '/become-author',
    path: '/become-author',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAssetsRoute =
  authenticatedDashboardAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedBillingSuccessRoute =
  authenticatedBillingSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => authenticatedBillingRouteRoute,
  } as any)
const authenticatedBillingCancelRoute =
  authenticatedBillingCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => authenticatedBillingRouteRoute,
  } as any)
const authenticatedAdminUsersRoute = authenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => authenticatedAdminRouteRoute,
} as any)
const authenticatedAdminStorageRoute =
  authenticatedAdminStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminRbacRoute = authenticatedAdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => authenticatedAdminRouteRoute,
} as any)
const authenticatedAccountAccountViewRoute =
  authenticatedAccountAccountViewRouteImport.update({
    id: '/$accountView',
    path: '/$accountView',
    getParentRoute: () => authenticatedAccountRouteRoute,
  } as any)
const authPagesAuthAuthViewRoute = authPagesAuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authenticatedAdminBillingRouteRoute =
  authenticatedAdminBillingRouteRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBlogIndexRoute =
  authenticatedAdminBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBillingIndexRoute =
  authenticatedAdminBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedAdminBillingRouteRoute,
  } as any)
const authenticatedAdminApiIndexRoute =
  authenticatedAdminApiIndexRouteImport.update({
    id: '/api/',
    path: '/api/',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const ApiV1PostsSlugRoute = ApiV1PostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiV1PostsRoute,
} as any)
const ApiStorageFilesSplatRoute = ApiStorageFilesSplatRouteImport.update({
  id: '/api/storage/files/$',
  path: '/api/storage/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageAvatarUserIdRoute = ApiStorageAvatarUserIdRouteImport.update({
  id: '/api/storage/avatar/$userId',
  path: '/api/storage/avatar/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasskeyVerifyRegistrationRoute =
  ApiAuthPasskeyVerifyRegistrationRouteImport.update({
    id: '/api/auth/passkey/verify-registration',
    path: '/api/auth/passkey/verify-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPasskeySignInRoute = ApiAuthPasskeySignInRouteImport.update({
  id: '/api/auth/passkey/sign-in',
  path: '/api/auth/passkey/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasskeyRegistrationOptionsRoute =
  ApiAuthPasskeyRegistrationOptionsRouteImport.update({
    id: '/api/auth/passkey/registration-options',
    path: '/api/auth/passkey/registration-options',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPasskeyAddPasskeyRoute =
  ApiAuthPasskeyAddPasskeyRouteImport.update({
    id: '/api/auth/passkey/add-passkey',
    path: '/api/auth/passkey/add-passkey',
    getParentRoute: () => rootRouteImport,
  } as any)
const blogSitesSiteSlugPageSlugRoute =
  blogSitesSiteSlugPageSlugRouteImport.update({
    id: '/sites/$siteSlug/$pageSlug',
    path: '/sites/$siteSlug/$pageSlug',
    getParentRoute: () => blogRouteRoute,
  } as any)
const authenticatedOrgSlugOrganizationViewRoute =
  authenticatedOrgSlugOrganizationViewRouteImport.update({
    id: '/org/$slug/$organizationView',
    path: '/org/$slug/$organizationView',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdminOrganizationOrganizationViewRoute =
  authenticatedAdminOrganizationOrganizationViewRouteImport.update({
    id: '/organization/$organizationView',
    path: '/organization/$organizationView',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBlogTagsRoute =
  authenticatedAdminBlogTagsRouteImport.update({
    id: '/blog/tags',
    path: '/blog/tags',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBlogSitesRoute =
  authenticatedAdminBlogSitesRouteImport.update({
    id: '/blog/sites',
    path: '/blog/sites',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBlogNewsletterRoute =
  authenticatedAdminBlogNewsletterRouteImport.update({
    id: '/blog/newsletter',
    path: '/blog/newsletter',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBlogMediaRoute =
  authenticatedAdminBlogMediaRouteImport.update({
    id: '/blog/media',
    path: '/blog/media',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBlogCommentsRoute =
  authenticatedAdminBlogCommentsRouteImport.update({
    id: '/blog/comments',
    path: '/blog/comments',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBlogCategoriesRoute =
  authenticatedAdminBlogCategoriesRouteImport.update({
    id: '/blog/categories',
    path: '/blog/categories',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBlogAuthorsRoute =
  authenticatedAdminBlogAuthorsRouteImport.update({
    id: '/blog/authors',
    path: '/blog/authors',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBlogAnalyticsRoute =
  authenticatedAdminBlogAnalyticsRouteImport.update({
    id: '/blog/analytics',
    path: '/blog/analytics',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBillingSubscriptionsRoute =
  authenticatedAdminBillingSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => authenticatedAdminBillingRouteRoute,
  } as any)
const authenticatedAdminBillingCustomersRoute =
  authenticatedAdminBillingCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => authenticatedAdminBillingRouteRoute,
  } as any)
const authenticatedAdminBillingCreditsRoute =
  authenticatedAdminBillingCreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => authenticatedAdminBillingRouteRoute,
  } as any)
const authenticatedAdminApiNewRoute =
  authenticatedAdminApiNewRouteImport.update({
    id: '/api/new',
    path: '/api/new',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminApiKeyIdRoute =
  authenticatedAdminApiKeyIdRouteImport.update({
    id: '/api/$keyId',
    path: '/api/$keyId',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAccountOrganizationsOrganizationViewRoute =
  authenticatedAccountOrganizationsOrganizationViewRouteImport.update({
    id: '/organizations/$organizationView',
    path: '/organizations/$organizationView',
    getParentRoute: () => authenticatedAccountRouteRoute,
  } as any)
const authenticatedAccountOrganizationOrganizationViewRoute =
  authenticatedAccountOrganizationOrganizationViewRouteImport.update({
    id: '/organization/$organizationView',
    path: '/organization/$organizationView',
    getParentRoute: () => authenticatedAccountRouteRoute,
  } as any)
const authPagesAuthCallbackVerifyEmailRoute =
  authPagesAuthCallbackVerifyEmailRouteImport.update({
    id: '/auth/callback/verify-email',
    path: '/auth/callback/verify-email',
    getParentRoute: () => authPagesRouteRoute,
  } as any)
const authPagesAuthCallbackAcceptInvitationRoute =
  authPagesAuthCallbackAcceptInvitationRouteImport.update({
    id: '/auth/callback/accept-invitation',
    path: '/auth/callback/accept-invitation',
    getParentRoute: () => authPagesRouteRoute,
  } as any)
const authenticatedAdminBlogPostsIndexRoute =
  authenticatedAdminBlogPostsIndexRouteImport.update({
    id: '/blog/posts/',
    path: '/blog/posts/',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBlogPostsNewRoute =
  authenticatedAdminBlogPostsNewRouteImport.update({
    id: '/blog/posts/new',
    path: '/blog/posts/new',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAccountOrganizationsSlugOrganizationViewRoute =
  authenticatedAccountOrganizationsSlugOrganizationViewRouteImport.update({
    id: '/organizations/$slug/$organizationView',
    path: '/organizations/$slug/$organizationView',
    getParentRoute: () => authenticatedAccountRouteRoute,
  } as any)
const authenticatedAccountOrganizationSlugOrganizationViewRoute =
  authenticatedAccountOrganizationSlugOrganizationViewRouteImport.update({
    id: '/organization/$slug/$organizationView',
    path: '/organization/$slug/$organizationView',
    getParentRoute: () => authenticatedAccountRouteRoute,
  } as any)
const authenticatedAdminBlogPostsPostIdEditRoute =
  authenticatedAdminBlogPostsPostIdEditRouteImport.update({
    id: '/blog/posts/$postId/edit',
    path: '/blog/posts/$postId/edit',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/cookies': typeof CookiesRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/terms': typeof TermsRouteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof authenticatedAccountRouteRouteWithChildren
  '/admin': typeof authenticatedAdminRouteRouteWithChildren
  '/billing': typeof authenticatedBillingRouteRouteWithChildren
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/editor': typeof authenticatedEditorRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/logout': typeof authPagesLogoutRoute
  '/signup': typeof authPagesSignupRoute
  '/$slug': typeof blogSlugRoute
  '/about': typeof blogAboutRoute
  '/author-onboarding': typeof blogAuthorOnboardingRoute
  '/authors': typeof blogAuthorsRoute
  '/search': typeof blogSearchRoute
  '/topics': typeof blogTopicsRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/': typeof blogIndexRoute
  '/admin/billing': typeof authenticatedAdminBillingRouteRouteWithChildren
  '/auth/$authView': typeof authPagesAuthAuthViewRoute
  '/account/$accountView': typeof authenticatedAccountAccountViewRoute
  '/admin/rbac': typeof authenticatedAdminRbacRoute
  '/admin/storage': typeof authenticatedAdminStorageRoute
  '/admin/users': typeof authenticatedAdminUsersRoute
  '/billing/cancel': typeof authenticatedBillingCancelRoute
  '/billing/success': typeof authenticatedBillingSuccessRoute
  '/dashboard/assets': typeof authenticatedDashboardAssetsRoute
  '/dashboard/become-author': typeof authenticatedDashboardBecomeAuthorRoute
  '/editor/new': typeof authenticatedEditorNewRoute
  '/errors/$error': typeof authenticatedErrorsErrorRoute
  '/org/$organizationView': typeof authenticatedOrgOrganizationViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/inngest/inngest': typeof ApiInngestInngestRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/v1/authors': typeof ApiV1AuthorsRoute
  '/api/v1/categories': typeof ApiV1CategoriesRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/api/v1/tags': typeof ApiV1TagsRoute
  '/auth/': typeof authPagesAuthIndexRoute
  '/account/': typeof authenticatedAccountIndexRoute
  '/admin/': typeof authenticatedAdminIndexRoute
  '/billing/': typeof authenticatedBillingIndexRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
  '/@$username/': typeof blogAtusernameIndexRoute
  '/auth/callback/accept-invitation': typeof authPagesAuthCallbackAcceptInvitationRoute
  '/auth/callback/verify-email': typeof authPagesAuthCallbackVerifyEmailRoute
  '/account/organization/$organizationView': typeof authenticatedAccountOrganizationOrganizationViewRoute
  '/account/organizations/$organizationView': typeof authenticatedAccountOrganizationsOrganizationViewRoute
  '/admin/api/$keyId': typeof authenticatedAdminApiKeyIdRoute
  '/admin/api/new': typeof authenticatedAdminApiNewRoute
  '/admin/billing/credits': typeof authenticatedAdminBillingCreditsRoute
  '/admin/billing/customers': typeof authenticatedAdminBillingCustomersRoute
  '/admin/billing/subscriptions': typeof authenticatedAdminBillingSubscriptionsRoute
  '/admin/blog/analytics': typeof authenticatedAdminBlogAnalyticsRoute
  '/admin/blog/authors': typeof authenticatedAdminBlogAuthorsRoute
  '/admin/blog/categories': typeof authenticatedAdminBlogCategoriesRoute
  '/admin/blog/comments': typeof authenticatedAdminBlogCommentsRoute
  '/admin/blog/media': typeof authenticatedAdminBlogMediaRoute
  '/admin/blog/newsletter': typeof authenticatedAdminBlogNewsletterRoute
  '/admin/blog/sites': typeof authenticatedAdminBlogSitesRoute
  '/admin/blog/tags': typeof authenticatedAdminBlogTagsRoute
  '/admin/organization/$organizationView': typeof authenticatedAdminOrganizationOrganizationViewRoute
  '/org/$slug/$organizationView': typeof authenticatedOrgSlugOrganizationViewRoute
  '/sites/$siteSlug/$pageSlug': typeof blogSitesSiteSlugPageSlugRoute
  '/api/auth/passkey/add-passkey': typeof ApiAuthPasskeyAddPasskeyRoute
  '/api/auth/passkey/registration-options': typeof ApiAuthPasskeyRegistrationOptionsRoute
  '/api/auth/passkey/sign-in': typeof ApiAuthPasskeySignInRoute
  '/api/auth/passkey/verify-registration': typeof ApiAuthPasskeyVerifyRegistrationRoute
  '/api/storage/avatar/$userId': typeof ApiStorageAvatarUserIdRoute
  '/api/storage/files/$': typeof ApiStorageFilesSplatRoute
  '/api/v1/posts/$slug': typeof ApiV1PostsSlugRoute
  '/admin/api/': typeof authenticatedAdminApiIndexRoute
  '/admin/billing/': typeof authenticatedAdminBillingIndexRoute
  '/admin/blog/': typeof authenticatedAdminBlogIndexRoute
  '/account/organization/$slug/$organizationView': typeof authenticatedAccountOrganizationSlugOrganizationViewRoute
  '/account/organizations/$slug/$organizationView': typeof authenticatedAccountOrganizationsSlugOrganizationViewRoute
  '/admin/blog/posts/new': typeof authenticatedAdminBlogPostsNewRoute
  '/admin/blog/posts/': typeof authenticatedAdminBlogPostsIndexRoute
  '/admin/blog/posts/$postId/edit': typeof authenticatedAdminBlogPostsPostIdEditRoute
}
export interface FileRoutesByTo {
  '/cookies': typeof CookiesRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/terms': typeof TermsRouteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/editor': typeof authenticatedEditorRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/logout': typeof authPagesLogoutRoute
  '/signup': typeof authPagesSignupRoute
  '/$slug': typeof blogSlugRoute
  '/about': typeof blogAboutRoute
  '/author-onboarding': typeof blogAuthorOnboardingRoute
  '/authors': typeof blogAuthorsRoute
  '/search': typeof blogSearchRoute
  '/topics': typeof blogTopicsRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/': typeof blogIndexRoute
  '/auth/$authView': typeof authPagesAuthAuthViewRoute
  '/account/$accountView': typeof authenticatedAccountAccountViewRoute
  '/admin/rbac': typeof authenticatedAdminRbacRoute
  '/admin/storage': typeof authenticatedAdminStorageRoute
  '/admin/users': typeof authenticatedAdminUsersRoute
  '/billing/cancel': typeof authenticatedBillingCancelRoute
  '/billing/success': typeof authenticatedBillingSuccessRoute
  '/dashboard/assets': typeof authenticatedDashboardAssetsRoute
  '/dashboard/become-author': typeof authenticatedDashboardBecomeAuthorRoute
  '/editor/new': typeof authenticatedEditorNewRoute
  '/errors/$error': typeof authenticatedErrorsErrorRoute
  '/org/$organizationView': typeof authenticatedOrgOrganizationViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/inngest/inngest': typeof ApiInngestInngestRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/v1/authors': typeof ApiV1AuthorsRoute
  '/api/v1/categories': typeof ApiV1CategoriesRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/api/v1/tags': typeof ApiV1TagsRoute
  '/auth': typeof authPagesAuthIndexRoute
  '/account': typeof authenticatedAccountIndexRoute
  '/admin': typeof authenticatedAdminIndexRoute
  '/billing': typeof authenticatedBillingIndexRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/@$username': typeof blogAtusernameIndexRoute
  '/auth/callback/accept-invitation': typeof authPagesAuthCallbackAcceptInvitationRoute
  '/auth/callback/verify-email': typeof authPagesAuthCallbackVerifyEmailRoute
  '/account/organization/$organizationView': typeof authenticatedAccountOrganizationOrganizationViewRoute
  '/account/organizations/$organizationView': typeof authenticatedAccountOrganizationsOrganizationViewRoute
  '/admin/api/$keyId': typeof authenticatedAdminApiKeyIdRoute
  '/admin/api/new': typeof authenticatedAdminApiNewRoute
  '/admin/billing/credits': typeof authenticatedAdminBillingCreditsRoute
  '/admin/billing/customers': typeof authenticatedAdminBillingCustomersRoute
  '/admin/billing/subscriptions': typeof authenticatedAdminBillingSubscriptionsRoute
  '/admin/blog/analytics': typeof authenticatedAdminBlogAnalyticsRoute
  '/admin/blog/authors': typeof authenticatedAdminBlogAuthorsRoute
  '/admin/blog/categories': typeof authenticatedAdminBlogCategoriesRoute
  '/admin/blog/comments': typeof authenticatedAdminBlogCommentsRoute
  '/admin/blog/media': typeof authenticatedAdminBlogMediaRoute
  '/admin/blog/newsletter': typeof authenticatedAdminBlogNewsletterRoute
  '/admin/blog/sites': typeof authenticatedAdminBlogSitesRoute
  '/admin/blog/tags': typeof authenticatedAdminBlogTagsRoute
  '/admin/organization/$organizationView': typeof authenticatedAdminOrganizationOrganizationViewRoute
  '/org/$slug/$organizationView': typeof authenticatedOrgSlugOrganizationViewRoute
  '/sites/$siteSlug/$pageSlug': typeof blogSitesSiteSlugPageSlugRoute
  '/api/auth/passkey/add-passkey': typeof ApiAuthPasskeyAddPasskeyRoute
  '/api/auth/passkey/registration-options': typeof ApiAuthPasskeyRegistrationOptionsRoute
  '/api/auth/passkey/sign-in': typeof ApiAuthPasskeySignInRoute
  '/api/auth/passkey/verify-registration': typeof ApiAuthPasskeyVerifyRegistrationRoute
  '/api/storage/avatar/$userId': typeof ApiStorageAvatarUserIdRoute
  '/api/storage/files/$': typeof ApiStorageFilesSplatRoute
  '/api/v1/posts/$slug': typeof ApiV1PostsSlugRoute
  '/admin/api': typeof authenticatedAdminApiIndexRoute
  '/admin/billing': typeof authenticatedAdminBillingIndexRoute
  '/admin/blog': typeof authenticatedAdminBlogIndexRoute
  '/account/organization/$slug/$organizationView': typeof authenticatedAccountOrganizationSlugOrganizationViewRoute
  '/account/organizations/$slug/$organizationView': typeof authenticatedAccountOrganizationsSlugOrganizationViewRoute
  '/admin/blog/posts/new': typeof authenticatedAdminBlogPostsNewRoute
  '/admin/blog/posts': typeof authenticatedAdminBlogPostsIndexRoute
  '/admin/blog/posts/$postId/edit': typeof authenticatedAdminBlogPostsPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(blog)': typeof blogRouteRouteWithChildren
  '/cookies': typeof CookiesRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/terms': typeof TermsRouteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(authenticated)/account': typeof authenticatedAccountRouteRouteWithChildren
  '/(authenticated)/admin': typeof authenticatedAdminRouteRouteWithChildren
  '/(authenticated)/billing': typeof authenticatedBillingRouteRouteWithChildren
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/(authenticated)/editor': typeof authenticatedEditorRouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(auth-pages)/logout': typeof authPagesLogoutRoute
  '/(auth-pages)/signup': typeof authPagesSignupRoute
  '/(blog)/$slug': typeof blogSlugRoute
  '/(blog)/about': typeof blogAboutRoute
  '/(blog)/author-onboarding': typeof blogAuthorOnboardingRoute
  '/(blog)/authors': typeof blogAuthorsRoute
  '/(blog)/search': typeof blogSearchRoute
  '/(blog)/topics': typeof blogTopicsRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/(blog)/': typeof blogIndexRoute
  '/(authenticated)/admin/billing': typeof authenticatedAdminBillingRouteRouteWithChildren
  '/(auth-pages)/auth/$authView': typeof authPagesAuthAuthViewRoute
  '/(authenticated)/account/$accountView': typeof authenticatedAccountAccountViewRoute
  '/(authenticated)/admin/rbac': typeof authenticatedAdminRbacRoute
  '/(authenticated)/admin/storage': typeof authenticatedAdminStorageRoute
  '/(authenticated)/admin/users': typeof authenticatedAdminUsersRoute
  '/(authenticated)/billing/cancel': typeof authenticatedBillingCancelRoute
  '/(authenticated)/billing/success': typeof authenticatedBillingSuccessRoute
  '/(authenticated)/dashboard/assets': typeof authenticatedDashboardAssetsRoute
  '/(authenticated)/dashboard/become-author': typeof authenticatedDashboardBecomeAuthorRoute
  '/(authenticated)/editor/new': typeof authenticatedEditorNewRoute
  '/(authenticated)/errors/$error': typeof authenticatedErrorsErrorRoute
  '/(authenticated)/org/$organizationView': typeof authenticatedOrgOrganizationViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/inngest/inngest': typeof ApiInngestInngestRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/v1/authors': typeof ApiV1AuthorsRoute
  '/api/v1/categories': typeof ApiV1CategoriesRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/api/v1/tags': typeof ApiV1TagsRoute
  '/(auth-pages)/auth/': typeof authPagesAuthIndexRoute
  '/(authenticated)/account/': typeof authenticatedAccountIndexRoute
  '/(authenticated)/admin/': typeof authenticatedAdminIndexRoute
  '/(authenticated)/billing/': typeof authenticatedBillingIndexRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/(blog)/@$username/': typeof blogAtusernameIndexRoute
  '/(auth-pages)/auth/callback/accept-invitation': typeof authPagesAuthCallbackAcceptInvitationRoute
  '/(auth-pages)/auth/callback/verify-email': typeof authPagesAuthCallbackVerifyEmailRoute
  '/(authenticated)/account/organization/$organizationView': typeof authenticatedAccountOrganizationOrganizationViewRoute
  '/(authenticated)/account/organizations/$organizationView': typeof authenticatedAccountOrganizationsOrganizationViewRoute
  '/(authenticated)/admin/api/$keyId': typeof authenticatedAdminApiKeyIdRoute
  '/(authenticated)/admin/api/new': typeof authenticatedAdminApiNewRoute
  '/(authenticated)/admin/billing/credits': typeof authenticatedAdminBillingCreditsRoute
  '/(authenticated)/admin/billing/customers': typeof authenticatedAdminBillingCustomersRoute
  '/(authenticated)/admin/billing/subscriptions': typeof authenticatedAdminBillingSubscriptionsRoute
  '/(authenticated)/admin/blog/analytics': typeof authenticatedAdminBlogAnalyticsRoute
  '/(authenticated)/admin/blog/authors': typeof authenticatedAdminBlogAuthorsRoute
  '/(authenticated)/admin/blog/categories': typeof authenticatedAdminBlogCategoriesRoute
  '/(authenticated)/admin/blog/comments': typeof authenticatedAdminBlogCommentsRoute
  '/(authenticated)/admin/blog/media': typeof authenticatedAdminBlogMediaRoute
  '/(authenticated)/admin/blog/newsletter': typeof authenticatedAdminBlogNewsletterRoute
  '/(authenticated)/admin/blog/sites': typeof authenticatedAdminBlogSitesRoute
  '/(authenticated)/admin/blog/tags': typeof authenticatedAdminBlogTagsRoute
  '/(authenticated)/admin/organization/$organizationView': typeof authenticatedAdminOrganizationOrganizationViewRoute
  '/(authenticated)/org/$slug/$organizationView': typeof authenticatedOrgSlugOrganizationViewRoute
  '/(blog)/sites/$siteSlug/$pageSlug': typeof blogSitesSiteSlugPageSlugRoute
  '/api/auth/passkey/add-passkey': typeof ApiAuthPasskeyAddPasskeyRoute
  '/api/auth/passkey/registration-options': typeof ApiAuthPasskeyRegistrationOptionsRoute
  '/api/auth/passkey/sign-in': typeof ApiAuthPasskeySignInRoute
  '/api/auth/passkey/verify-registration': typeof ApiAuthPasskeyVerifyRegistrationRoute
  '/api/storage/avatar/$userId': typeof ApiStorageAvatarUserIdRoute
  '/api/storage/files/$': typeof ApiStorageFilesSplatRoute
  '/api/v1/posts/$slug': typeof ApiV1PostsSlugRoute
  '/(authenticated)/admin/api/': typeof authenticatedAdminApiIndexRoute
  '/(authenticated)/admin/billing/': typeof authenticatedAdminBillingIndexRoute
  '/(authenticated)/admin/blog/': typeof authenticatedAdminBlogIndexRoute
  '/(authenticated)/account/organization/$slug/$organizationView': typeof authenticatedAccountOrganizationSlugOrganizationViewRoute
  '/(authenticated)/account/organizations/$slug/$organizationView': typeof authenticatedAccountOrganizationsSlugOrganizationViewRoute
  '/(authenticated)/admin/blog/posts/new': typeof authenticatedAdminBlogPostsNewRoute
  '/(authenticated)/admin/blog/posts/': typeof authenticatedAdminBlogPostsIndexRoute
  '/(authenticated)/admin/blog/posts/$postId/edit': typeof authenticatedAdminBlogPostsPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/editor'
    | '/login'
    | '/logout'
    | '/signup'
    | '/$slug'
    | '/about'
    | '/author-onboarding'
    | '/authors'
    | '/search'
    | '/topics'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/newsletter/confirm'
    | '/'
    | '/admin/billing'
    | '/auth/$authView'
    | '/account/$accountView'
    | '/admin/rbac'
    | '/admin/storage'
    | '/admin/users'
    | '/billing/cancel'
    | '/billing/success'
    | '/dashboard/assets'
    | '/dashboard/become-author'
    | '/editor/new'
    | '/errors/$error'
    | '/org/$organizationView'
    | '/api/auth/$'
    | '/api/inngest/inngest'
    | '/api/storage/upload'
    | '/api/v1/authors'
    | '/api/v1/categories'
    | '/api/v1/posts'
    | '/api/v1/tags'
    | '/auth/'
    | '/account/'
    | '/admin/'
    | '/billing/'
    | '/dashboard/'
    | '/@$username/'
    | '/auth/callback/accept-invitation'
    | '/auth/callback/verify-email'
    | '/account/organization/$organizationView'
    | '/account/organizations/$organizationView'
    | '/admin/api/$keyId'
    | '/admin/api/new'
    | '/admin/billing/credits'
    | '/admin/billing/customers'
    | '/admin/billing/subscriptions'
    | '/admin/blog/analytics'
    | '/admin/blog/authors'
    | '/admin/blog/categories'
    | '/admin/blog/comments'
    | '/admin/blog/media'
    | '/admin/blog/newsletter'
    | '/admin/blog/sites'
    | '/admin/blog/tags'
    | '/admin/organization/$organizationView'
    | '/org/$slug/$organizationView'
    | '/sites/$siteSlug/$pageSlug'
    | '/api/auth/passkey/add-passkey'
    | '/api/auth/passkey/registration-options'
    | '/api/auth/passkey/sign-in'
    | '/api/auth/passkey/verify-registration'
    | '/api/storage/avatar/$userId'
    | '/api/storage/files/$'
    | '/api/v1/posts/$slug'
    | '/admin/api/'
    | '/admin/billing/'
    | '/admin/blog/'
    | '/account/organization/$slug/$organizationView'
    | '/account/organizations/$slug/$organizationView'
    | '/admin/blog/posts/new'
    | '/admin/blog/posts/'
    | '/admin/blog/posts/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/sitemap.xml'
    | '/editor'
    | '/login'
    | '/logout'
    | '/signup'
    | '/$slug'
    | '/about'
    | '/author-onboarding'
    | '/authors'
    | '/search'
    | '/topics'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/newsletter/confirm'
    | '/'
    | '/auth/$authView'
    | '/account/$accountView'
    | '/admin/rbac'
    | '/admin/storage'
    | '/admin/users'
    | '/billing/cancel'
    | '/billing/success'
    | '/dashboard/assets'
    | '/dashboard/become-author'
    | '/editor/new'
    | '/errors/$error'
    | '/org/$organizationView'
    | '/api/auth/$'
    | '/api/inngest/inngest'
    | '/api/storage/upload'
    | '/api/v1/authors'
    | '/api/v1/categories'
    | '/api/v1/posts'
    | '/api/v1/tags'
    | '/auth'
    | '/account'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/@$username'
    | '/auth/callback/accept-invitation'
    | '/auth/callback/verify-email'
    | '/account/organization/$organizationView'
    | '/account/organizations/$organizationView'
    | '/admin/api/$keyId'
    | '/admin/api/new'
    | '/admin/billing/credits'
    | '/admin/billing/customers'
    | '/admin/billing/subscriptions'
    | '/admin/blog/analytics'
    | '/admin/blog/authors'
    | '/admin/blog/categories'
    | '/admin/blog/comments'
    | '/admin/blog/media'
    | '/admin/blog/newsletter'
    | '/admin/blog/sites'
    | '/admin/blog/tags'
    | '/admin/organization/$organizationView'
    | '/org/$slug/$organizationView'
    | '/sites/$siteSlug/$pageSlug'
    | '/api/auth/passkey/add-passkey'
    | '/api/auth/passkey/registration-options'
    | '/api/auth/passkey/sign-in'
    | '/api/auth/passkey/verify-registration'
    | '/api/storage/avatar/$userId'
    | '/api/storage/files/$'
    | '/api/v1/posts/$slug'
    | '/admin/api'
    | '/admin/billing'
    | '/admin/blog'
    | '/account/organization/$slug/$organizationView'
    | '/account/organizations/$slug/$organizationView'
    | '/admin/blog/posts/new'
    | '/admin/blog/posts'
    | '/admin/blog/posts/$postId/edit'
  id:
    | '__root__'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/(blog)'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/sitemap.xml'
    | '/(authenticated)/account'
    | '/(authenticated)/admin'
    | '/(authenticated)/billing'
    | '/(authenticated)/dashboard'
    | '/(authenticated)/editor'
    | '/(auth-pages)/login'
    | '/(auth-pages)/logout'
    | '/(auth-pages)/signup'
    | '/(blog)/$slug'
    | '/(blog)/about'
    | '/(blog)/author-onboarding'
    | '/(blog)/authors'
    | '/(blog)/search'
    | '/(blog)/topics'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/newsletter/confirm'
    | '/(blog)/'
    | '/(authenticated)/admin/billing'
    | '/(auth-pages)/auth/$authView'
    | '/(authenticated)/account/$accountView'
    | '/(authenticated)/admin/rbac'
    | '/(authenticated)/admin/storage'
    | '/(authenticated)/admin/users'
    | '/(authenticated)/billing/cancel'
    | '/(authenticated)/billing/success'
    | '/(authenticated)/dashboard/assets'
    | '/(authenticated)/dashboard/become-author'
    | '/(authenticated)/editor/new'
    | '/(authenticated)/errors/$error'
    | '/(authenticated)/org/$organizationView'
    | '/api/auth/$'
    | '/api/inngest/inngest'
    | '/api/storage/upload'
    | '/api/v1/authors'
    | '/api/v1/categories'
    | '/api/v1/posts'
    | '/api/v1/tags'
    | '/(auth-pages)/auth/'
    | '/(authenticated)/account/'
    | '/(authenticated)/admin/'
    | '/(authenticated)/billing/'
    | '/(authenticated)/dashboard/'
    | '/(blog)/@$username/'
    | '/(auth-pages)/auth/callback/accept-invitation'
    | '/(auth-pages)/auth/callback/verify-email'
    | '/(authenticated)/account/organization/$organizationView'
    | '/(authenticated)/account/organizations/$organizationView'
    | '/(authenticated)/admin/api/$keyId'
    | '/(authenticated)/admin/api/new'
    | '/(authenticated)/admin/billing/credits'
    | '/(authenticated)/admin/billing/customers'
    | '/(authenticated)/admin/billing/subscriptions'
    | '/(authenticated)/admin/blog/analytics'
    | '/(authenticated)/admin/blog/authors'
    | '/(authenticated)/admin/blog/categories'
    | '/(authenticated)/admin/blog/comments'
    | '/(authenticated)/admin/blog/media'
    | '/(authenticated)/admin/blog/newsletter'
    | '/(authenticated)/admin/blog/sites'
    | '/(authenticated)/admin/blog/tags'
    | '/(authenticated)/admin/organization/$organizationView'
    | '/(authenticated)/org/$slug/$organizationView'
    | '/(blog)/sites/$siteSlug/$pageSlug'
    | '/api/auth/passkey/add-passkey'
    | '/api/auth/passkey/registration-options'
    | '/api/auth/passkey/sign-in'
    | '/api/auth/passkey/verify-registration'
    | '/api/storage/avatar/$userId'
    | '/api/storage/files/$'
    | '/api/v1/posts/$slug'
    | '/(authenticated)/admin/api/'
    | '/(authenticated)/admin/billing/'
    | '/(authenticated)/admin/blog/'
    | '/(authenticated)/account/organization/$slug/$organizationView'
    | '/(authenticated)/account/organizations/$slug/$organizationView'
    | '/(authenticated)/admin/blog/posts/new'
    | '/(authenticated)/admin/blog/posts/'
    | '/(authenticated)/admin/blog/posts/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  blogRouteRoute: typeof blogRouteRouteWithChildren
  CookiesRouteRoute: typeof CookiesRouteRoute
  PrivacyRouteRoute: typeof PrivacyRouteRoute
  TermsRouteRoute: typeof TermsRouteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  NewsletterConfirmRoute: typeof NewsletterConfirmRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInngestInngestRoute: typeof ApiInngestInngestRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiV1AuthorsRoute: typeof ApiV1AuthorsRoute
  ApiV1CategoriesRoute: typeof ApiV1CategoriesRoute
  ApiV1PostsRoute: typeof ApiV1PostsRouteWithChildren
  ApiV1TagsRoute: typeof ApiV1TagsRoute
  ApiAuthPasskeyAddPasskeyRoute: typeof ApiAuthPasskeyAddPasskeyRoute
  ApiAuthPasskeyRegistrationOptionsRoute: typeof ApiAuthPasskeyRegistrationOptionsRoute
  ApiAuthPasskeySignInRoute: typeof ApiAuthPasskeySignInRoute
  ApiAuthPasskeyVerifyRegistrationRoute: typeof ApiAuthPasskeyVerifyRegistrationRoute
  ApiStorageAvatarUserIdRoute: typeof ApiStorageAvatarUserIdRoute
  ApiStorageFilesSplatRoute: typeof ApiStorageFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)': {
      id: '/(blog)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof blogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/': {
      id: '/(blog)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof blogIndexRouteImport
      parentRoute: typeof blogRouteRoute
    }
    '/newsletter/confirm': {
      id: '/newsletter/confirm'
      path: '/newsletter/confirm'
      fullPath: '/newsletter/confirm'
      preLoaderRoute: typeof NewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/topics': {
      id: '/(blog)/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof blogTopicsRouteImport
      parentRoute: typeof blogRouteRoute
    }
    '/(blog)/search': {
      id: '/(blog)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof blogSearchRouteImport
      parentRoute: typeof blogRouteRoute
    }
    '/(blog)/authors': {
      id: '/(blog)/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof blogAuthorsRouteImport
      parentRoute: typeof blogRouteRoute
    }
    '/(blog)/author-onboarding': {
      id: '/(blog)/author-onboarding'
      path: '/author-onboarding'
      fullPath: '/author-onboarding'
      preLoaderRoute: typeof blogAuthorOnboardingRouteImport
      parentRoute: typeof blogRouteRoute
    }
    '/(blog)/about': {
      id: '/(blog)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof blogAboutRouteImport
      parentRoute: typeof blogRouteRoute
    }
    '/(blog)/$slug': {
      id: '/(blog)/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof blogSlugRouteImport
      parentRoute: typeof blogRouteRoute
    }
    '/(auth-pages)/signup': {
      id: '/(auth-pages)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/logout': {
      id: '/(auth-pages)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authPagesLogoutRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(authenticated)/editor': {
      id: '/(authenticated)/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof authenticatedEditorRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/billing': {
      id: '/(authenticated)/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof authenticatedBillingRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/admin': {
      id: '/(authenticated)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authenticatedAdminRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/account': {
      id: '/(authenticated)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof authenticatedAccountRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(blog)/@$username/': {
      id: '/(blog)/@$username/'
      path: '/@$username'
      fullPath: '/@$username/'
      preLoaderRoute: typeof blogAtusernameIndexRouteImport
      parentRoute: typeof blogRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/billing/': {
      id: '/(authenticated)/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof authenticatedBillingIndexRouteImport
      parentRoute: typeof authenticatedBillingRouteRoute
    }
    '/(authenticated)/admin/': {
      id: '/(authenticated)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof authenticatedAdminIndexRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/account/': {
      id: '/(authenticated)/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof authenticatedAccountIndexRouteImport
      parentRoute: typeof authenticatedAccountRouteRoute
    }
    '/(auth-pages)/auth/': {
      id: '/(auth-pages)/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof authPagesAuthIndexRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/api/v1/tags': {
      id: '/api/v1/tags'
      path: '/api/v1/tags'
      fullPath: '/api/v1/tags'
      preLoaderRoute: typeof ApiV1TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts': {
      id: '/api/v1/posts'
      path: '/api/v1/posts'
      fullPath: '/api/v1/posts'
      preLoaderRoute: typeof ApiV1PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/categories': {
      id: '/api/v1/categories'
      path: '/api/v1/categories'
      fullPath: '/api/v1/categories'
      preLoaderRoute: typeof ApiV1CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/authors': {
      id: '/api/v1/authors'
      path: '/api/v1/authors'
      fullPath: '/api/v1/authors'
      preLoaderRoute: typeof ApiV1AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest/inngest': {
      id: '/api/inngest/inngest'
      path: '/api/inngest/inngest'
      fullPath: '/api/inngest/inngest'
      preLoaderRoute: typeof ApiInngestInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/org/$organizationView': {
      id: '/(authenticated)/org/$organizationView'
      path: '/org/$organizationView'
      fullPath: '/org/$organizationView'
      preLoaderRoute: typeof authenticatedOrgOrganizationViewRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/errors/$error': {
      id: '/(authenticated)/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof authenticatedErrorsErrorRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/editor/new': {
      id: '/(authenticated)/editor/new'
      path: '/new'
      fullPath: '/editor/new'
      preLoaderRoute: typeof authenticatedEditorNewRouteImport
      parentRoute: typeof authenticatedEditorRouteRoute
    }
    '/(authenticated)/dashboard/become-author': {
      id: '/(authenticated)/dashboard/become-author'
      path: '/become-author'
      fullPath: '/dashboard/become-author'
      preLoaderRoute: typeof authenticatedDashboardBecomeAuthorRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/assets': {
      id: '/(authenticated)/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof authenticatedDashboardAssetsRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/billing/success': {
      id: '/(authenticated)/billing/success'
      path: '/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof authenticatedBillingSuccessRouteImport
      parentRoute: typeof authenticatedBillingRouteRoute
    }
    '/(authenticated)/billing/cancel': {
      id: '/(authenticated)/billing/cancel'
      path: '/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof authenticatedBillingCancelRouteImport
      parentRoute: typeof authenticatedBillingRouteRoute
    }
    '/(authenticated)/admin/users': {
      id: '/(authenticated)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof authenticatedAdminUsersRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/storage': {
      id: '/(authenticated)/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof authenticatedAdminStorageRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/rbac': {
      id: '/(authenticated)/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof authenticatedAdminRbacRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/account/$accountView': {
      id: '/(authenticated)/account/$accountView'
      path: '/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof authenticatedAccountAccountViewRouteImport
      parentRoute: typeof authenticatedAccountRouteRoute
    }
    '/(auth-pages)/auth/$authView': {
      id: '/(auth-pages)/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof authPagesAuthAuthViewRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(authenticated)/admin/billing': {
      id: '/(authenticated)/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof authenticatedAdminBillingRouteRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/blog/': {
      id: '/(authenticated)/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof authenticatedAdminBlogIndexRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/billing/': {
      id: '/(authenticated)/admin/billing/'
      path: '/'
      fullPath: '/admin/billing/'
      preLoaderRoute: typeof authenticatedAdminBillingIndexRouteImport
      parentRoute: typeof authenticatedAdminBillingRouteRoute
    }
    '/(authenticated)/admin/api/': {
      id: '/(authenticated)/admin/api/'
      path: '/api'
      fullPath: '/admin/api/'
      preLoaderRoute: typeof authenticatedAdminApiIndexRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/api/v1/posts/$slug': {
      id: '/api/v1/posts/$slug'
      path: '/$slug'
      fullPath: '/api/v1/posts/$slug'
      preLoaderRoute: typeof ApiV1PostsSlugRouteImport
      parentRoute: typeof ApiV1PostsRoute
    }
    '/api/storage/files/$': {
      id: '/api/storage/files/$'
      path: '/api/storage/files/$'
      fullPath: '/api/storage/files/$'
      preLoaderRoute: typeof ApiStorageFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/avatar/$userId': {
      id: '/api/storage/avatar/$userId'
      path: '/api/storage/avatar/$userId'
      fullPath: '/api/storage/avatar/$userId'
      preLoaderRoute: typeof ApiStorageAvatarUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/verify-registration': {
      id: '/api/auth/passkey/verify-registration'
      path: '/api/auth/passkey/verify-registration'
      fullPath: '/api/auth/passkey/verify-registration'
      preLoaderRoute: typeof ApiAuthPasskeyVerifyRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/sign-in': {
      id: '/api/auth/passkey/sign-in'
      path: '/api/auth/passkey/sign-in'
      fullPath: '/api/auth/passkey/sign-in'
      preLoaderRoute: typeof ApiAuthPasskeySignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/registration-options': {
      id: '/api/auth/passkey/registration-options'
      path: '/api/auth/passkey/registration-options'
      fullPath: '/api/auth/passkey/registration-options'
      preLoaderRoute: typeof ApiAuthPasskeyRegistrationOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/add-passkey': {
      id: '/api/auth/passkey/add-passkey'
      path: '/api/auth/passkey/add-passkey'
      fullPath: '/api/auth/passkey/add-passkey'
      preLoaderRoute: typeof ApiAuthPasskeyAddPasskeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/sites/$siteSlug/$pageSlug': {
      id: '/(blog)/sites/$siteSlug/$pageSlug'
      path: '/sites/$siteSlug/$pageSlug'
      fullPath: '/sites/$siteSlug/$pageSlug'
      preLoaderRoute: typeof blogSitesSiteSlugPageSlugRouteImport
      parentRoute: typeof blogRouteRoute
    }
    '/(authenticated)/org/$slug/$organizationView': {
      id: '/(authenticated)/org/$slug/$organizationView'
      path: '/org/$slug/$organizationView'
      fullPath: '/org/$slug/$organizationView'
      preLoaderRoute: typeof authenticatedOrgSlugOrganizationViewRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/admin/organization/$organizationView': {
      id: '/(authenticated)/admin/organization/$organizationView'
      path: '/organization/$organizationView'
      fullPath: '/admin/organization/$organizationView'
      preLoaderRoute: typeof authenticatedAdminOrganizationOrganizationViewRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/blog/tags': {
      id: '/(authenticated)/admin/blog/tags'
      path: '/blog/tags'
      fullPath: '/admin/blog/tags'
      preLoaderRoute: typeof authenticatedAdminBlogTagsRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/blog/sites': {
      id: '/(authenticated)/admin/blog/sites'
      path: '/blog/sites'
      fullPath: '/admin/blog/sites'
      preLoaderRoute: typeof authenticatedAdminBlogSitesRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/blog/newsletter': {
      id: '/(authenticated)/admin/blog/newsletter'
      path: '/blog/newsletter'
      fullPath: '/admin/blog/newsletter'
      preLoaderRoute: typeof authenticatedAdminBlogNewsletterRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/blog/media': {
      id: '/(authenticated)/admin/blog/media'
      path: '/blog/media'
      fullPath: '/admin/blog/media'
      preLoaderRoute: typeof authenticatedAdminBlogMediaRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/blog/comments': {
      id: '/(authenticated)/admin/blog/comments'
      path: '/blog/comments'
      fullPath: '/admin/blog/comments'
      preLoaderRoute: typeof authenticatedAdminBlogCommentsRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/blog/categories': {
      id: '/(authenticated)/admin/blog/categories'
      path: '/blog/categories'
      fullPath: '/admin/blog/categories'
      preLoaderRoute: typeof authenticatedAdminBlogCategoriesRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/blog/authors': {
      id: '/(authenticated)/admin/blog/authors'
      path: '/blog/authors'
      fullPath: '/admin/blog/authors'
      preLoaderRoute: typeof authenticatedAdminBlogAuthorsRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/blog/analytics': {
      id: '/(authenticated)/admin/blog/analytics'
      path: '/blog/analytics'
      fullPath: '/admin/blog/analytics'
      preLoaderRoute: typeof authenticatedAdminBlogAnalyticsRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/billing/subscriptions': {
      id: '/(authenticated)/admin/billing/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/billing/subscriptions'
      preLoaderRoute: typeof authenticatedAdminBillingSubscriptionsRouteImport
      parentRoute: typeof authenticatedAdminBillingRouteRoute
    }
    '/(authenticated)/admin/billing/customers': {
      id: '/(authenticated)/admin/billing/customers'
      path: '/customers'
      fullPath: '/admin/billing/customers'
      preLoaderRoute: typeof authenticatedAdminBillingCustomersRouteImport
      parentRoute: typeof authenticatedAdminBillingRouteRoute
    }
    '/(authenticated)/admin/billing/credits': {
      id: '/(authenticated)/admin/billing/credits'
      path: '/credits'
      fullPath: '/admin/billing/credits'
      preLoaderRoute: typeof authenticatedAdminBillingCreditsRouteImport
      parentRoute: typeof authenticatedAdminBillingRouteRoute
    }
    '/(authenticated)/admin/api/new': {
      id: '/(authenticated)/admin/api/new'
      path: '/api/new'
      fullPath: '/admin/api/new'
      preLoaderRoute: typeof authenticatedAdminApiNewRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/api/$keyId': {
      id: '/(authenticated)/admin/api/$keyId'
      path: '/api/$keyId'
      fullPath: '/admin/api/$keyId'
      preLoaderRoute: typeof authenticatedAdminApiKeyIdRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/account/organizations/$organizationView': {
      id: '/(authenticated)/account/organizations/$organizationView'
      path: '/organizations/$organizationView'
      fullPath: '/account/organizations/$organizationView'
      preLoaderRoute: typeof authenticatedAccountOrganizationsOrganizationViewRouteImport
      parentRoute: typeof authenticatedAccountRouteRoute
    }
    '/(authenticated)/account/organization/$organizationView': {
      id: '/(authenticated)/account/organization/$organizationView'
      path: '/organization/$organizationView'
      fullPath: '/account/organization/$organizationView'
      preLoaderRoute: typeof authenticatedAccountOrganizationOrganizationViewRouteImport
      parentRoute: typeof authenticatedAccountRouteRoute
    }
    '/(auth-pages)/auth/callback/verify-email': {
      id: '/(auth-pages)/auth/callback/verify-email'
      path: '/auth/callback/verify-email'
      fullPath: '/auth/callback/verify-email'
      preLoaderRoute: typeof authPagesAuthCallbackVerifyEmailRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/auth/callback/accept-invitation': {
      id: '/(auth-pages)/auth/callback/accept-invitation'
      path: '/auth/callback/accept-invitation'
      fullPath: '/auth/callback/accept-invitation'
      preLoaderRoute: typeof authPagesAuthCallbackAcceptInvitationRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(authenticated)/admin/blog/posts/': {
      id: '/(authenticated)/admin/blog/posts/'
      path: '/blog/posts'
      fullPath: '/admin/blog/posts/'
      preLoaderRoute: typeof authenticatedAdminBlogPostsIndexRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/blog/posts/new': {
      id: '/(authenticated)/admin/blog/posts/new'
      path: '/blog/posts/new'
      fullPath: '/admin/blog/posts/new'
      preLoaderRoute: typeof authenticatedAdminBlogPostsNewRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/account/organizations/$slug/$organizationView': {
      id: '/(authenticated)/account/organizations/$slug/$organizationView'
      path: '/organizations/$slug/$organizationView'
      fullPath: '/account/organizations/$slug/$organizationView'
      preLoaderRoute: typeof authenticatedAccountOrganizationsSlugOrganizationViewRouteImport
      parentRoute: typeof authenticatedAccountRouteRoute
    }
    '/(authenticated)/account/organization/$slug/$organizationView': {
      id: '/(authenticated)/account/organization/$slug/$organizationView'
      path: '/organization/$slug/$organizationView'
      fullPath: '/account/organization/$slug/$organizationView'
      preLoaderRoute: typeof authenticatedAccountOrganizationSlugOrganizationViewRouteImport
      parentRoute: typeof authenticatedAccountRouteRoute
    }
    '/(authenticated)/admin/blog/posts/$postId/edit': {
      id: '/(authenticated)/admin/blog/posts/$postId/edit'
      path: '/blog/posts/$postId/edit'
      fullPath: '/admin/blog/posts/$postId/edit'
      preLoaderRoute: typeof authenticatedAdminBlogPostsPostIdEditRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesLogoutRoute: typeof authPagesLogoutRoute
  authPagesSignupRoute: typeof authPagesSignupRoute
  authPagesAuthAuthViewRoute: typeof authPagesAuthAuthViewRoute
  authPagesAuthIndexRoute: typeof authPagesAuthIndexRoute
  authPagesAuthCallbackAcceptInvitationRoute: typeof authPagesAuthCallbackAcceptInvitationRoute
  authPagesAuthCallbackVerifyEmailRoute: typeof authPagesAuthCallbackVerifyEmailRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesLogoutRoute: authPagesLogoutRoute,
  authPagesSignupRoute: authPagesSignupRoute,
  authPagesAuthAuthViewRoute: authPagesAuthAuthViewRoute,
  authPagesAuthIndexRoute: authPagesAuthIndexRoute,
  authPagesAuthCallbackAcceptInvitationRoute:
    authPagesAuthCallbackAcceptInvitationRoute,
  authPagesAuthCallbackVerifyEmailRoute: authPagesAuthCallbackVerifyEmailRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedAccountRouteRouteChildren {
  authenticatedAccountAccountViewRoute: typeof authenticatedAccountAccountViewRoute
  authenticatedAccountIndexRoute: typeof authenticatedAccountIndexRoute
  authenticatedAccountOrganizationOrganizationViewRoute: typeof authenticatedAccountOrganizationOrganizationViewRoute
  authenticatedAccountOrganizationsOrganizationViewRoute: typeof authenticatedAccountOrganizationsOrganizationViewRoute
  authenticatedAccountOrganizationSlugOrganizationViewRoute: typeof authenticatedAccountOrganizationSlugOrganizationViewRoute
  authenticatedAccountOrganizationsSlugOrganizationViewRoute: typeof authenticatedAccountOrganizationsSlugOrganizationViewRoute
}

const authenticatedAccountRouteRouteChildren: authenticatedAccountRouteRouteChildren =
  {
    authenticatedAccountAccountViewRoute: authenticatedAccountAccountViewRoute,
    authenticatedAccountIndexRoute: authenticatedAccountIndexRoute,
    authenticatedAccountOrganizationOrganizationViewRoute:
      authenticatedAccountOrganizationOrganizationViewRoute,
    authenticatedAccountOrganizationsOrganizationViewRoute:
      authenticatedAccountOrganizationsOrganizationViewRoute,
    authenticatedAccountOrganizationSlugOrganizationViewRoute:
      authenticatedAccountOrganizationSlugOrganizationViewRoute,
    authenticatedAccountOrganizationsSlugOrganizationViewRoute:
      authenticatedAccountOrganizationsSlugOrganizationViewRoute,
  }

const authenticatedAccountRouteRouteWithChildren =
  authenticatedAccountRouteRoute._addFileChildren(
    authenticatedAccountRouteRouteChildren,
  )

interface authenticatedAdminBillingRouteRouteChildren {
  authenticatedAdminBillingCreditsRoute: typeof authenticatedAdminBillingCreditsRoute
  authenticatedAdminBillingCustomersRoute: typeof authenticatedAdminBillingCustomersRoute
  authenticatedAdminBillingSubscriptionsRoute: typeof authenticatedAdminBillingSubscriptionsRoute
  authenticatedAdminBillingIndexRoute: typeof authenticatedAdminBillingIndexRoute
}

const authenticatedAdminBillingRouteRouteChildren: authenticatedAdminBillingRouteRouteChildren =
  {
    authenticatedAdminBillingCreditsRoute:
      authenticatedAdminBillingCreditsRoute,
    authenticatedAdminBillingCustomersRoute:
      authenticatedAdminBillingCustomersRoute,
    authenticatedAdminBillingSubscriptionsRoute:
      authenticatedAdminBillingSubscriptionsRoute,
    authenticatedAdminBillingIndexRoute: authenticatedAdminBillingIndexRoute,
  }

const authenticatedAdminBillingRouteRouteWithChildren =
  authenticatedAdminBillingRouteRoute._addFileChildren(
    authenticatedAdminBillingRouteRouteChildren,
  )

interface authenticatedAdminRouteRouteChildren {
  authenticatedAdminBillingRouteRoute: typeof authenticatedAdminBillingRouteRouteWithChildren
  authenticatedAdminRbacRoute: typeof authenticatedAdminRbacRoute
  authenticatedAdminStorageRoute: typeof authenticatedAdminStorageRoute
  authenticatedAdminUsersRoute: typeof authenticatedAdminUsersRoute
  authenticatedAdminIndexRoute: typeof authenticatedAdminIndexRoute
  authenticatedAdminApiKeyIdRoute: typeof authenticatedAdminApiKeyIdRoute
  authenticatedAdminApiNewRoute: typeof authenticatedAdminApiNewRoute
  authenticatedAdminBlogAnalyticsRoute: typeof authenticatedAdminBlogAnalyticsRoute
  authenticatedAdminBlogAuthorsRoute: typeof authenticatedAdminBlogAuthorsRoute
  authenticatedAdminBlogCategoriesRoute: typeof authenticatedAdminBlogCategoriesRoute
  authenticatedAdminBlogCommentsRoute: typeof authenticatedAdminBlogCommentsRoute
  authenticatedAdminBlogMediaRoute: typeof authenticatedAdminBlogMediaRoute
  authenticatedAdminBlogNewsletterRoute: typeof authenticatedAdminBlogNewsletterRoute
  authenticatedAdminBlogSitesRoute: typeof authenticatedAdminBlogSitesRoute
  authenticatedAdminBlogTagsRoute: typeof authenticatedAdminBlogTagsRoute
  authenticatedAdminOrganizationOrganizationViewRoute: typeof authenticatedAdminOrganizationOrganizationViewRoute
  authenticatedAdminApiIndexRoute: typeof authenticatedAdminApiIndexRoute
  authenticatedAdminBlogIndexRoute: typeof authenticatedAdminBlogIndexRoute
  authenticatedAdminBlogPostsNewRoute: typeof authenticatedAdminBlogPostsNewRoute
  authenticatedAdminBlogPostsIndexRoute: typeof authenticatedAdminBlogPostsIndexRoute
  authenticatedAdminBlogPostsPostIdEditRoute: typeof authenticatedAdminBlogPostsPostIdEditRoute
}

const authenticatedAdminRouteRouteChildren: authenticatedAdminRouteRouteChildren =
  {
    authenticatedAdminBillingRouteRoute:
      authenticatedAdminBillingRouteRouteWithChildren,
    authenticatedAdminRbacRoute: authenticatedAdminRbacRoute,
    authenticatedAdminStorageRoute: authenticatedAdminStorageRoute,
    authenticatedAdminUsersRoute: authenticatedAdminUsersRoute,
    authenticatedAdminIndexRoute: authenticatedAdminIndexRoute,
    authenticatedAdminApiKeyIdRoute: authenticatedAdminApiKeyIdRoute,
    authenticatedAdminApiNewRoute: authenticatedAdminApiNewRoute,
    authenticatedAdminBlogAnalyticsRoute: authenticatedAdminBlogAnalyticsRoute,
    authenticatedAdminBlogAuthorsRoute: authenticatedAdminBlogAuthorsRoute,
    authenticatedAdminBlogCategoriesRoute:
      authenticatedAdminBlogCategoriesRoute,
    authenticatedAdminBlogCommentsRoute: authenticatedAdminBlogCommentsRoute,
    authenticatedAdminBlogMediaRoute: authenticatedAdminBlogMediaRoute,
    authenticatedAdminBlogNewsletterRoute:
      authenticatedAdminBlogNewsletterRoute,
    authenticatedAdminBlogSitesRoute: authenticatedAdminBlogSitesRoute,
    authenticatedAdminBlogTagsRoute: authenticatedAdminBlogTagsRoute,
    authenticatedAdminOrganizationOrganizationViewRoute:
      authenticatedAdminOrganizationOrganizationViewRoute,
    authenticatedAdminApiIndexRoute: authenticatedAdminApiIndexRoute,
    authenticatedAdminBlogIndexRoute: authenticatedAdminBlogIndexRoute,
    authenticatedAdminBlogPostsNewRoute: authenticatedAdminBlogPostsNewRoute,
    authenticatedAdminBlogPostsIndexRoute:
      authenticatedAdminBlogPostsIndexRoute,
    authenticatedAdminBlogPostsPostIdEditRoute:
      authenticatedAdminBlogPostsPostIdEditRoute,
  }

const authenticatedAdminRouteRouteWithChildren =
  authenticatedAdminRouteRoute._addFileChildren(
    authenticatedAdminRouteRouteChildren,
  )

interface authenticatedBillingRouteRouteChildren {
  authenticatedBillingCancelRoute: typeof authenticatedBillingCancelRoute
  authenticatedBillingSuccessRoute: typeof authenticatedBillingSuccessRoute
  authenticatedBillingIndexRoute: typeof authenticatedBillingIndexRoute
}

const authenticatedBillingRouteRouteChildren: authenticatedBillingRouteRouteChildren =
  {
    authenticatedBillingCancelRoute: authenticatedBillingCancelRoute,
    authenticatedBillingSuccessRoute: authenticatedBillingSuccessRoute,
    authenticatedBillingIndexRoute: authenticatedBillingIndexRoute,
  }

const authenticatedBillingRouteRouteWithChildren =
  authenticatedBillingRouteRoute._addFileChildren(
    authenticatedBillingRouteRouteChildren,
  )

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardAssetsRoute: typeof authenticatedDashboardAssetsRoute
  authenticatedDashboardBecomeAuthorRoute: typeof authenticatedDashboardBecomeAuthorRoute
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardAssetsRoute: authenticatedDashboardAssetsRoute,
    authenticatedDashboardBecomeAuthorRoute:
      authenticatedDashboardBecomeAuthorRoute,
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedEditorRouteRouteChildren {
  authenticatedEditorNewRoute: typeof authenticatedEditorNewRoute
}

const authenticatedEditorRouteRouteChildren: authenticatedEditorRouteRouteChildren =
  {
    authenticatedEditorNewRoute: authenticatedEditorNewRoute,
  }

const authenticatedEditorRouteRouteWithChildren =
  authenticatedEditorRouteRoute._addFileChildren(
    authenticatedEditorRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedAccountRouteRoute: typeof authenticatedAccountRouteRouteWithChildren
  authenticatedAdminRouteRoute: typeof authenticatedAdminRouteRouteWithChildren
  authenticatedBillingRouteRoute: typeof authenticatedBillingRouteRouteWithChildren
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
  authenticatedEditorRouteRoute: typeof authenticatedEditorRouteRouteWithChildren
  authenticatedErrorsErrorRoute: typeof authenticatedErrorsErrorRoute
  authenticatedOrgOrganizationViewRoute: typeof authenticatedOrgOrganizationViewRoute
  authenticatedOrgSlugOrganizationViewRoute: typeof authenticatedOrgSlugOrganizationViewRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedAccountRouteRoute: authenticatedAccountRouteRouteWithChildren,
  authenticatedAdminRouteRoute: authenticatedAdminRouteRouteWithChildren,
  authenticatedBillingRouteRoute: authenticatedBillingRouteRouteWithChildren,
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
  authenticatedEditorRouteRoute: authenticatedEditorRouteRouteWithChildren,
  authenticatedErrorsErrorRoute: authenticatedErrorsErrorRoute,
  authenticatedOrgOrganizationViewRoute: authenticatedOrgOrganizationViewRoute,
  authenticatedOrgSlugOrganizationViewRoute:
    authenticatedOrgSlugOrganizationViewRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface blogRouteRouteChildren {
  blogSlugRoute: typeof blogSlugRoute
  blogAboutRoute: typeof blogAboutRoute
  blogAuthorOnboardingRoute: typeof blogAuthorOnboardingRoute
  blogAuthorsRoute: typeof blogAuthorsRoute
  blogSearchRoute: typeof blogSearchRoute
  blogTopicsRoute: typeof blogTopicsRoute
  blogIndexRoute: typeof blogIndexRoute
  blogAtusernameIndexRoute: typeof blogAtusernameIndexRoute
  blogSitesSiteSlugPageSlugRoute: typeof blogSitesSiteSlugPageSlugRoute
}

const blogRouteRouteChildren: blogRouteRouteChildren = {
  blogSlugRoute: blogSlugRoute,
  blogAboutRoute: blogAboutRoute,
  blogAuthorOnboardingRoute: blogAuthorOnboardingRoute,
  blogAuthorsRoute: blogAuthorsRoute,
  blogSearchRoute: blogSearchRoute,
  blogTopicsRoute: blogTopicsRoute,
  blogIndexRoute: blogIndexRoute,
  blogAtusernameIndexRoute: blogAtusernameIndexRoute,
  blogSitesSiteSlugPageSlugRoute: blogSitesSiteSlugPageSlugRoute,
}

const blogRouteRouteWithChildren = blogRouteRoute._addFileChildren(
  blogRouteRouteChildren,
)

interface ApiV1PostsRouteChildren {
  ApiV1PostsSlugRoute: typeof ApiV1PostsSlugRoute
}

const ApiV1PostsRouteChildren: ApiV1PostsRouteChildren = {
  ApiV1PostsSlugRoute: ApiV1PostsSlugRoute,
}

const ApiV1PostsRouteWithChildren = ApiV1PostsRoute._addFileChildren(
  ApiV1PostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  blogRouteRoute: blogRouteRouteWithChildren,
  CookiesRouteRoute: CookiesRouteRoute,
  PrivacyRouteRoute: PrivacyRouteRoute,
  TermsRouteRoute: TermsRouteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  NewsletterConfirmRoute: NewsletterConfirmRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInngestInngestRoute: ApiInngestInngestRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiV1AuthorsRoute: ApiV1AuthorsRoute,
  ApiV1CategoriesRoute: ApiV1CategoriesRoute,
  ApiV1PostsRoute: ApiV1PostsRouteWithChildren,
  ApiV1TagsRoute: ApiV1TagsRoute,
  ApiAuthPasskeyAddPasskeyRoute: ApiAuthPasskeyAddPasskeyRoute,
  ApiAuthPasskeyRegistrationOptionsRoute:
    ApiAuthPasskeyRegistrationOptionsRoute,
  ApiAuthPasskeySignInRoute: ApiAuthPasskeySignInRoute,
  ApiAuthPasskeyVerifyRegistrationRoute: ApiAuthPasskeyVerifyRegistrationRoute,
  ApiStorageAvatarUserIdRoute: ApiStorageAvatarUserIdRoute,
  ApiStorageFilesSplatRoute: ApiStorageFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
