/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteRouteImport } from './routes/terms/route'
import { Route as PrivacyRouteRouteImport } from './routes/privacy/route'
import { Route as CookiesRouteRouteImport } from './routes/cookies/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authPagesSignupRouteImport } from './routes/(auth-pages)/signup'
import { Route as authPagesLogoutRouteImport } from './routes/(auth-pages)/logout'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as authenticatedBillingRouteRouteImport } from './routes/(authenticated)/billing/route'
import { Route as authenticatedAdminRouteRouteImport } from './routes/(authenticated)/admin/route'
import { Route as authenticatedAccountRouteRouteImport } from './routes/(authenticated)/account/route'
import { Route as authenticatedBillingIndexRouteImport } from './routes/(authenticated)/billing/index'
import { Route as authenticatedAdminIndexRouteImport } from './routes/(authenticated)/admin/index'
import { Route as authenticatedAccountIndexRouteImport } from './routes/(authenticated)/account/index'
import { Route as authPagesAuthIndexRouteImport } from './routes/(auth-pages)/auth/index'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiInngestInngestRouteImport } from './routes/api/inngest/inngest'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedErrorsErrorRouteImport } from './routes/(authenticated)/errors/$error'
import { Route as authenticatedBillingSuccessRouteImport } from './routes/(authenticated)/billing/success'
import { Route as authenticatedBillingCancelRouteImport } from './routes/(authenticated)/billing/cancel'
import { Route as authenticatedAdminUsersRouteImport } from './routes/(authenticated)/admin/users'
import { Route as authenticatedAdminStorageRouteImport } from './routes/(authenticated)/admin/storage'
import { Route as authenticatedAdminShippingRouteImport } from './routes/(authenticated)/admin/shipping'
import { Route as authenticatedAdminReviewsRouteImport } from './routes/(authenticated)/admin/reviews'
import { Route as authenticatedAdminRbacRouteImport } from './routes/(authenticated)/admin/rbac'
import { Route as authenticatedAdminInventoryRouteImport } from './routes/(authenticated)/admin/inventory'
import { Route as authenticatedAdminCustomersRouteImport } from './routes/(authenticated)/admin/customers'
import { Route as authenticatedAdminCouponsRouteImport } from './routes/(authenticated)/admin/coupons'
import { Route as authenticatedAccountAccountViewRouteImport } from './routes/(authenticated)/account/$accountView'
import { Route as authPagesAuthAuthViewRouteImport } from './routes/(auth-pages)/auth/$authView'
import { Route as authenticatedAdminProductsRouteRouteImport } from './routes/(authenticated)/admin/products/route'
import { Route as authenticatedAdminOrdersRouteRouteImport } from './routes/(authenticated)/admin/orders/route'
import { Route as authenticatedAdminBillingRouteRouteImport } from './routes/(authenticated)/admin/billing/route'
import { Route as authenticatedAdminProductsIndexRouteImport } from './routes/(authenticated)/admin/products/index'
import { Route as authenticatedAdminOrdersIndexRouteImport } from './routes/(authenticated)/admin/orders/index'
import { Route as authenticatedAdminBillingIndexRouteImport } from './routes/(authenticated)/admin/billing/index'
import { Route as ApiStorageFilesSplatRouteImport } from './routes/api/storage/files/$'
import { Route as ApiStorageAvatarUserIdRouteImport } from './routes/api/storage/avatar/$userId'
import { Route as ApiAuthPasskeyVerifyRegistrationRouteImport } from './routes/api/auth/passkey/verify-registration'
import { Route as ApiAuthPasskeySignInRouteImport } from './routes/api/auth/passkey/sign-in'
import { Route as ApiAuthPasskeyRegistrationOptionsRouteImport } from './routes/api/auth/passkey/registration-options'
import { Route as ApiAuthPasskeyAddPasskeyRouteImport } from './routes/api/auth/passkey/add-passkey'
import { Route as authenticatedAdminProductsNewRouteImport } from './routes/(authenticated)/admin/products/new'
import { Route as authenticatedAdminProductsProductIdRouteImport } from './routes/(authenticated)/admin/products/$productId'
import { Route as authenticatedAdminOrdersOrderIdRouteImport } from './routes/(authenticated)/admin/orders/$orderId'
import { Route as authenticatedAdminBillingSubscriptionsRouteImport } from './routes/(authenticated)/admin/billing/subscriptions'
import { Route as authenticatedAdminBillingCustomersRouteImport } from './routes/(authenticated)/admin/billing/customers'
import { Route as authenticatedAdminBillingCreditsRouteImport } from './routes/(authenticated)/admin/billing/credits'
import { Route as authPagesAuthCallbackVerifyEmailRouteImport } from './routes/(auth-pages)/auth/callback/verify-email'

const TermsRouteRoute = TermsRouteRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRouteRoute = PrivacyRouteRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRouteRoute = CookiesRouteRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesSignupRoute = authPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLogoutRoute = authPagesLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedBillingRouteRoute =
  authenticatedBillingRouteRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdminRouteRoute = authenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedAccountRouteRoute =
  authenticatedAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedBillingIndexRoute =
  authenticatedBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedBillingRouteRoute,
  } as any)
const authenticatedAdminIndexRoute = authenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedAdminRouteRoute,
} as any)
const authenticatedAccountIndexRoute =
  authenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedAccountRouteRoute,
  } as any)
const authPagesAuthIndexRoute = authPagesAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestInngestRoute = ApiInngestInngestRouteImport.update({
  id: '/api/inngest/inngest',
  path: '/api/inngest/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedErrorsErrorRoute =
  authenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedBillingSuccessRoute =
  authenticatedBillingSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => authenticatedBillingRouteRoute,
  } as any)
const authenticatedBillingCancelRoute =
  authenticatedBillingCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => authenticatedBillingRouteRoute,
  } as any)
const authenticatedAdminUsersRoute = authenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => authenticatedAdminRouteRoute,
} as any)
const authenticatedAdminStorageRoute =
  authenticatedAdminStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminShippingRoute =
  authenticatedAdminShippingRouteImport.update({
    id: '/shipping',
    path: '/shipping',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminReviewsRoute =
  authenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminRbacRoute = authenticatedAdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => authenticatedAdminRouteRoute,
} as any)
const authenticatedAdminInventoryRoute =
  authenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminCustomersRoute =
  authenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminCouponsRoute =
  authenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAccountAccountViewRoute =
  authenticatedAccountAccountViewRouteImport.update({
    id: '/$accountView',
    path: '/$accountView',
    getParentRoute: () => authenticatedAccountRouteRoute,
  } as any)
const authPagesAuthAuthViewRoute = authPagesAuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authenticatedAdminProductsRouteRoute =
  authenticatedAdminProductsRouteRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminOrdersRouteRoute =
  authenticatedAdminOrdersRouteRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminBillingRouteRoute =
  authenticatedAdminBillingRouteRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authenticatedAdminProductsIndexRoute =
  authenticatedAdminProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedAdminProductsRouteRoute,
  } as any)
const authenticatedAdminOrdersIndexRoute =
  authenticatedAdminOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedAdminOrdersRouteRoute,
  } as any)
const authenticatedAdminBillingIndexRoute =
  authenticatedAdminBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedAdminBillingRouteRoute,
  } as any)
const ApiStorageFilesSplatRoute = ApiStorageFilesSplatRouteImport.update({
  id: '/api/storage/files/$',
  path: '/api/storage/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageAvatarUserIdRoute = ApiStorageAvatarUserIdRouteImport.update({
  id: '/api/storage/avatar/$userId',
  path: '/api/storage/avatar/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasskeyVerifyRegistrationRoute =
  ApiAuthPasskeyVerifyRegistrationRouteImport.update({
    id: '/api/auth/passkey/verify-registration',
    path: '/api/auth/passkey/verify-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPasskeySignInRoute = ApiAuthPasskeySignInRouteImport.update({
  id: '/api/auth/passkey/sign-in',
  path: '/api/auth/passkey/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasskeyRegistrationOptionsRoute =
  ApiAuthPasskeyRegistrationOptionsRouteImport.update({
    id: '/api/auth/passkey/registration-options',
    path: '/api/auth/passkey/registration-options',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPasskeyAddPasskeyRoute =
  ApiAuthPasskeyAddPasskeyRouteImport.update({
    id: '/api/auth/passkey/add-passkey',
    path: '/api/auth/passkey/add-passkey',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedAdminProductsNewRoute =
  authenticatedAdminProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => authenticatedAdminProductsRouteRoute,
  } as any)
const authenticatedAdminProductsProductIdRoute =
  authenticatedAdminProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => authenticatedAdminProductsRouteRoute,
  } as any)
const authenticatedAdminOrdersOrderIdRoute =
  authenticatedAdminOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => authenticatedAdminOrdersRouteRoute,
  } as any)
const authenticatedAdminBillingSubscriptionsRoute =
  authenticatedAdminBillingSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => authenticatedAdminBillingRouteRoute,
  } as any)
const authenticatedAdminBillingCustomersRoute =
  authenticatedAdminBillingCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => authenticatedAdminBillingRouteRoute,
  } as any)
const authenticatedAdminBillingCreditsRoute =
  authenticatedAdminBillingCreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => authenticatedAdminBillingRouteRoute,
  } as any)
const authPagesAuthCallbackVerifyEmailRoute =
  authPagesAuthCallbackVerifyEmailRouteImport.update({
    id: '/auth/callback/verify-email',
    path: '/auth/callback/verify-email',
    getParentRoute: () => authPagesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/terms': typeof TermsRouteRoute
  '/account': typeof authenticatedAccountRouteRouteWithChildren
  '/admin': typeof authenticatedAdminRouteRouteWithChildren
  '/billing': typeof authenticatedBillingRouteRouteWithChildren
  '/dashboard': typeof authenticatedDashboardRouteRoute
  '/login': typeof authPagesLoginRoute
  '/logout': typeof authPagesLogoutRoute
  '/signup': typeof authPagesSignupRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin/billing': typeof authenticatedAdminBillingRouteRouteWithChildren
  '/admin/orders': typeof authenticatedAdminOrdersRouteRouteWithChildren
  '/admin/products': typeof authenticatedAdminProductsRouteRouteWithChildren
  '/auth/$authView': typeof authPagesAuthAuthViewRoute
  '/account/$accountView': typeof authenticatedAccountAccountViewRoute
  '/admin/coupons': typeof authenticatedAdminCouponsRoute
  '/admin/customers': typeof authenticatedAdminCustomersRoute
  '/admin/inventory': typeof authenticatedAdminInventoryRoute
  '/admin/rbac': typeof authenticatedAdminRbacRoute
  '/admin/reviews': typeof authenticatedAdminReviewsRoute
  '/admin/shipping': typeof authenticatedAdminShippingRoute
  '/admin/storage': typeof authenticatedAdminStorageRoute
  '/admin/users': typeof authenticatedAdminUsersRoute
  '/billing/cancel': typeof authenticatedBillingCancelRoute
  '/billing/success': typeof authenticatedBillingSuccessRoute
  '/errors/$error': typeof authenticatedErrorsErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/inngest/inngest': typeof ApiInngestInngestRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/auth': typeof authPagesAuthIndexRoute
  '/account/': typeof authenticatedAccountIndexRoute
  '/admin/': typeof authenticatedAdminIndexRoute
  '/billing/': typeof authenticatedBillingIndexRoute
  '/auth/callback/verify-email': typeof authPagesAuthCallbackVerifyEmailRoute
  '/admin/billing/credits': typeof authenticatedAdminBillingCreditsRoute
  '/admin/billing/customers': typeof authenticatedAdminBillingCustomersRoute
  '/admin/billing/subscriptions': typeof authenticatedAdminBillingSubscriptionsRoute
  '/admin/orders/$orderId': typeof authenticatedAdminOrdersOrderIdRoute
  '/admin/products/$productId': typeof authenticatedAdminProductsProductIdRoute
  '/admin/products/new': typeof authenticatedAdminProductsNewRoute
  '/api/auth/passkey/add-passkey': typeof ApiAuthPasskeyAddPasskeyRoute
  '/api/auth/passkey/registration-options': typeof ApiAuthPasskeyRegistrationOptionsRoute
  '/api/auth/passkey/sign-in': typeof ApiAuthPasskeySignInRoute
  '/api/auth/passkey/verify-registration': typeof ApiAuthPasskeyVerifyRegistrationRoute
  '/api/storage/avatar/$userId': typeof ApiStorageAvatarUserIdRoute
  '/api/storage/files/$': typeof ApiStorageFilesSplatRoute
  '/admin/billing/': typeof authenticatedAdminBillingIndexRoute
  '/admin/orders/': typeof authenticatedAdminOrdersIndexRoute
  '/admin/products/': typeof authenticatedAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/terms': typeof TermsRouteRoute
  '/dashboard': typeof authenticatedDashboardRouteRoute
  '/login': typeof authPagesLoginRoute
  '/logout': typeof authPagesLogoutRoute
  '/signup': typeof authPagesSignupRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/$authView': typeof authPagesAuthAuthViewRoute
  '/account/$accountView': typeof authenticatedAccountAccountViewRoute
  '/admin/coupons': typeof authenticatedAdminCouponsRoute
  '/admin/customers': typeof authenticatedAdminCustomersRoute
  '/admin/inventory': typeof authenticatedAdminInventoryRoute
  '/admin/rbac': typeof authenticatedAdminRbacRoute
  '/admin/reviews': typeof authenticatedAdminReviewsRoute
  '/admin/shipping': typeof authenticatedAdminShippingRoute
  '/admin/storage': typeof authenticatedAdminStorageRoute
  '/admin/users': typeof authenticatedAdminUsersRoute
  '/billing/cancel': typeof authenticatedBillingCancelRoute
  '/billing/success': typeof authenticatedBillingSuccessRoute
  '/errors/$error': typeof authenticatedErrorsErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/inngest/inngest': typeof ApiInngestInngestRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/auth': typeof authPagesAuthIndexRoute
  '/account': typeof authenticatedAccountIndexRoute
  '/admin': typeof authenticatedAdminIndexRoute
  '/billing': typeof authenticatedBillingIndexRoute
  '/auth/callback/verify-email': typeof authPagesAuthCallbackVerifyEmailRoute
  '/admin/billing/credits': typeof authenticatedAdminBillingCreditsRoute
  '/admin/billing/customers': typeof authenticatedAdminBillingCustomersRoute
  '/admin/billing/subscriptions': typeof authenticatedAdminBillingSubscriptionsRoute
  '/admin/orders/$orderId': typeof authenticatedAdminOrdersOrderIdRoute
  '/admin/products/$productId': typeof authenticatedAdminProductsProductIdRoute
  '/admin/products/new': typeof authenticatedAdminProductsNewRoute
  '/api/auth/passkey/add-passkey': typeof ApiAuthPasskeyAddPasskeyRoute
  '/api/auth/passkey/registration-options': typeof ApiAuthPasskeyRegistrationOptionsRoute
  '/api/auth/passkey/sign-in': typeof ApiAuthPasskeySignInRoute
  '/api/auth/passkey/verify-registration': typeof ApiAuthPasskeyVerifyRegistrationRoute
  '/api/storage/avatar/$userId': typeof ApiStorageAvatarUserIdRoute
  '/api/storage/files/$': typeof ApiStorageFilesSplatRoute
  '/admin/billing': typeof authenticatedAdminBillingIndexRoute
  '/admin/orders': typeof authenticatedAdminOrdersIndexRoute
  '/admin/products': typeof authenticatedAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/cookies': typeof CookiesRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/terms': typeof TermsRouteRoute
  '/(authenticated)/account': typeof authenticatedAccountRouteRouteWithChildren
  '/(authenticated)/admin': typeof authenticatedAdminRouteRouteWithChildren
  '/(authenticated)/billing': typeof authenticatedBillingRouteRouteWithChildren
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRoute
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(auth-pages)/logout': typeof authPagesLogoutRoute
  '/(auth-pages)/signup': typeof authPagesSignupRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(authenticated)/admin/billing': typeof authenticatedAdminBillingRouteRouteWithChildren
  '/(authenticated)/admin/orders': typeof authenticatedAdminOrdersRouteRouteWithChildren
  '/(authenticated)/admin/products': typeof authenticatedAdminProductsRouteRouteWithChildren
  '/(auth-pages)/auth/$authView': typeof authPagesAuthAuthViewRoute
  '/(authenticated)/account/$accountView': typeof authenticatedAccountAccountViewRoute
  '/(authenticated)/admin/coupons': typeof authenticatedAdminCouponsRoute
  '/(authenticated)/admin/customers': typeof authenticatedAdminCustomersRoute
  '/(authenticated)/admin/inventory': typeof authenticatedAdminInventoryRoute
  '/(authenticated)/admin/rbac': typeof authenticatedAdminRbacRoute
  '/(authenticated)/admin/reviews': typeof authenticatedAdminReviewsRoute
  '/(authenticated)/admin/shipping': typeof authenticatedAdminShippingRoute
  '/(authenticated)/admin/storage': typeof authenticatedAdminStorageRoute
  '/(authenticated)/admin/users': typeof authenticatedAdminUsersRoute
  '/(authenticated)/billing/cancel': typeof authenticatedBillingCancelRoute
  '/(authenticated)/billing/success': typeof authenticatedBillingSuccessRoute
  '/(authenticated)/errors/$error': typeof authenticatedErrorsErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/inngest/inngest': typeof ApiInngestInngestRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/(auth-pages)/auth/': typeof authPagesAuthIndexRoute
  '/(authenticated)/account/': typeof authenticatedAccountIndexRoute
  '/(authenticated)/admin/': typeof authenticatedAdminIndexRoute
  '/(authenticated)/billing/': typeof authenticatedBillingIndexRoute
  '/(auth-pages)/auth/callback/verify-email': typeof authPagesAuthCallbackVerifyEmailRoute
  '/(authenticated)/admin/billing/credits': typeof authenticatedAdminBillingCreditsRoute
  '/(authenticated)/admin/billing/customers': typeof authenticatedAdminBillingCustomersRoute
  '/(authenticated)/admin/billing/subscriptions': typeof authenticatedAdminBillingSubscriptionsRoute
  '/(authenticated)/admin/orders/$orderId': typeof authenticatedAdminOrdersOrderIdRoute
  '/(authenticated)/admin/products/$productId': typeof authenticatedAdminProductsProductIdRoute
  '/(authenticated)/admin/products/new': typeof authenticatedAdminProductsNewRoute
  '/api/auth/passkey/add-passkey': typeof ApiAuthPasskeyAddPasskeyRoute
  '/api/auth/passkey/registration-options': typeof ApiAuthPasskeyRegistrationOptionsRoute
  '/api/auth/passkey/sign-in': typeof ApiAuthPasskeySignInRoute
  '/api/auth/passkey/verify-registration': typeof ApiAuthPasskeyVerifyRegistrationRoute
  '/api/storage/avatar/$userId': typeof ApiStorageAvatarUserIdRoute
  '/api/storage/files/$': typeof ApiStorageFilesSplatRoute
  '/(authenticated)/admin/billing/': typeof authenticatedAdminBillingIndexRoute
  '/(authenticated)/admin/orders/': typeof authenticatedAdminOrdersIndexRoute
  '/(authenticated)/admin/products/': typeof authenticatedAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/signup'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin/billing'
    | '/admin/orders'
    | '/admin/products'
    | '/auth/$authView'
    | '/account/$accountView'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/rbac'
    | '/admin/reviews'
    | '/admin/shipping'
    | '/admin/storage'
    | '/admin/users'
    | '/billing/cancel'
    | '/billing/success'
    | '/errors/$error'
    | '/api/auth/$'
    | '/api/inngest/inngest'
    | '/api/storage/upload'
    | '/auth'
    | '/account/'
    | '/admin/'
    | '/billing/'
    | '/auth/callback/verify-email'
    | '/admin/billing/credits'
    | '/admin/billing/customers'
    | '/admin/billing/subscriptions'
    | '/admin/orders/$orderId'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/api/auth/passkey/add-passkey'
    | '/api/auth/passkey/registration-options'
    | '/api/auth/passkey/sign-in'
    | '/api/auth/passkey/verify-registration'
    | '/api/storage/avatar/$userId'
    | '/api/storage/files/$'
    | '/admin/billing/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/signup'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/$authView'
    | '/account/$accountView'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/rbac'
    | '/admin/reviews'
    | '/admin/shipping'
    | '/admin/storage'
    | '/admin/users'
    | '/billing/cancel'
    | '/billing/success'
    | '/errors/$error'
    | '/api/auth/$'
    | '/api/inngest/inngest'
    | '/api/storage/upload'
    | '/auth'
    | '/account'
    | '/admin'
    | '/billing'
    | '/auth/callback/verify-email'
    | '/admin/billing/credits'
    | '/admin/billing/customers'
    | '/admin/billing/subscriptions'
    | '/admin/orders/$orderId'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/api/auth/passkey/add-passkey'
    | '/api/auth/passkey/registration-options'
    | '/api/auth/passkey/sign-in'
    | '/api/auth/passkey/verify-registration'
    | '/api/storage/avatar/$userId'
    | '/api/storage/files/$'
    | '/admin/billing'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/(authenticated)/account'
    | '/(authenticated)/admin'
    | '/(authenticated)/billing'
    | '/(authenticated)/dashboard'
    | '/(auth-pages)/login'
    | '/(auth-pages)/logout'
    | '/(auth-pages)/signup'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(authenticated)/admin/billing'
    | '/(authenticated)/admin/orders'
    | '/(authenticated)/admin/products'
    | '/(auth-pages)/auth/$authView'
    | '/(authenticated)/account/$accountView'
    | '/(authenticated)/admin/coupons'
    | '/(authenticated)/admin/customers'
    | '/(authenticated)/admin/inventory'
    | '/(authenticated)/admin/rbac'
    | '/(authenticated)/admin/reviews'
    | '/(authenticated)/admin/shipping'
    | '/(authenticated)/admin/storage'
    | '/(authenticated)/admin/users'
    | '/(authenticated)/billing/cancel'
    | '/(authenticated)/billing/success'
    | '/(authenticated)/errors/$error'
    | '/api/auth/$'
    | '/api/inngest/inngest'
    | '/api/storage/upload'
    | '/(auth-pages)/auth/'
    | '/(authenticated)/account/'
    | '/(authenticated)/admin/'
    | '/(authenticated)/billing/'
    | '/(auth-pages)/auth/callback/verify-email'
    | '/(authenticated)/admin/billing/credits'
    | '/(authenticated)/admin/billing/customers'
    | '/(authenticated)/admin/billing/subscriptions'
    | '/(authenticated)/admin/orders/$orderId'
    | '/(authenticated)/admin/products/$productId'
    | '/(authenticated)/admin/products/new'
    | '/api/auth/passkey/add-passkey'
    | '/api/auth/passkey/registration-options'
    | '/api/auth/passkey/sign-in'
    | '/api/auth/passkey/verify-registration'
    | '/api/storage/avatar/$userId'
    | '/api/storage/files/$'
    | '/(authenticated)/admin/billing/'
    | '/(authenticated)/admin/orders/'
    | '/(authenticated)/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  CookiesRouteRoute: typeof CookiesRouteRoute
  PrivacyRouteRoute: typeof PrivacyRouteRoute
  TermsRouteRoute: typeof TermsRouteRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInngestInngestRoute: typeof ApiInngestInngestRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiAuthPasskeyAddPasskeyRoute: typeof ApiAuthPasskeyAddPasskeyRoute
  ApiAuthPasskeyRegistrationOptionsRoute: typeof ApiAuthPasskeyRegistrationOptionsRoute
  ApiAuthPasskeySignInRoute: typeof ApiAuthPasskeySignInRoute
  ApiAuthPasskeyVerifyRegistrationRoute: typeof ApiAuthPasskeyVerifyRegistrationRoute
  ApiStorageAvatarUserIdRoute: typeof ApiStorageAvatarUserIdRoute
  ApiStorageFilesSplatRoute: typeof ApiStorageFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)/signup': {
      id: '/(auth-pages)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/logout': {
      id: '/(auth-pages)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authPagesLogoutRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/billing': {
      id: '/(authenticated)/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof authenticatedBillingRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/admin': {
      id: '/(authenticated)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authenticatedAdminRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/account': {
      id: '/(authenticated)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof authenticatedAccountRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/billing/': {
      id: '/(authenticated)/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof authenticatedBillingIndexRouteImport
      parentRoute: typeof authenticatedBillingRouteRoute
    }
    '/(authenticated)/admin/': {
      id: '/(authenticated)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof authenticatedAdminIndexRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/account/': {
      id: '/(authenticated)/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof authenticatedAccountIndexRouteImport
      parentRoute: typeof authenticatedAccountRouteRoute
    }
    '/(auth-pages)/auth/': {
      id: '/(auth-pages)/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authPagesAuthIndexRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest/inngest': {
      id: '/api/inngest/inngest'
      path: '/api/inngest/inngest'
      fullPath: '/api/inngest/inngest'
      preLoaderRoute: typeof ApiInngestInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/errors/$error': {
      id: '/(authenticated)/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof authenticatedErrorsErrorRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/billing/success': {
      id: '/(authenticated)/billing/success'
      path: '/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof authenticatedBillingSuccessRouteImport
      parentRoute: typeof authenticatedBillingRouteRoute
    }
    '/(authenticated)/billing/cancel': {
      id: '/(authenticated)/billing/cancel'
      path: '/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof authenticatedBillingCancelRouteImport
      parentRoute: typeof authenticatedBillingRouteRoute
    }
    '/(authenticated)/admin/users': {
      id: '/(authenticated)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof authenticatedAdminUsersRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/storage': {
      id: '/(authenticated)/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof authenticatedAdminStorageRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/shipping': {
      id: '/(authenticated)/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof authenticatedAdminShippingRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/reviews': {
      id: '/(authenticated)/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof authenticatedAdminReviewsRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/rbac': {
      id: '/(authenticated)/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof authenticatedAdminRbacRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/inventory': {
      id: '/(authenticated)/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof authenticatedAdminInventoryRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/customers': {
      id: '/(authenticated)/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof authenticatedAdminCustomersRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/coupons': {
      id: '/(authenticated)/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof authenticatedAdminCouponsRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/account/$accountView': {
      id: '/(authenticated)/account/$accountView'
      path: '/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof authenticatedAccountAccountViewRouteImport
      parentRoute: typeof authenticatedAccountRouteRoute
    }
    '/(auth-pages)/auth/$authView': {
      id: '/(auth-pages)/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof authPagesAuthAuthViewRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(authenticated)/admin/products': {
      id: '/(authenticated)/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof authenticatedAdminProductsRouteRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/orders': {
      id: '/(authenticated)/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof authenticatedAdminOrdersRouteRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/billing': {
      id: '/(authenticated)/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof authenticatedAdminBillingRouteRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(authenticated)/admin/products/': {
      id: '/(authenticated)/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof authenticatedAdminProductsIndexRouteImport
      parentRoute: typeof authenticatedAdminProductsRouteRoute
    }
    '/(authenticated)/admin/orders/': {
      id: '/(authenticated)/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof authenticatedAdminOrdersIndexRouteImport
      parentRoute: typeof authenticatedAdminOrdersRouteRoute
    }
    '/(authenticated)/admin/billing/': {
      id: '/(authenticated)/admin/billing/'
      path: '/'
      fullPath: '/admin/billing/'
      preLoaderRoute: typeof authenticatedAdminBillingIndexRouteImport
      parentRoute: typeof authenticatedAdminBillingRouteRoute
    }
    '/api/storage/files/$': {
      id: '/api/storage/files/$'
      path: '/api/storage/files/$'
      fullPath: '/api/storage/files/$'
      preLoaderRoute: typeof ApiStorageFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/avatar/$userId': {
      id: '/api/storage/avatar/$userId'
      path: '/api/storage/avatar/$userId'
      fullPath: '/api/storage/avatar/$userId'
      preLoaderRoute: typeof ApiStorageAvatarUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/verify-registration': {
      id: '/api/auth/passkey/verify-registration'
      path: '/api/auth/passkey/verify-registration'
      fullPath: '/api/auth/passkey/verify-registration'
      preLoaderRoute: typeof ApiAuthPasskeyVerifyRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/sign-in': {
      id: '/api/auth/passkey/sign-in'
      path: '/api/auth/passkey/sign-in'
      fullPath: '/api/auth/passkey/sign-in'
      preLoaderRoute: typeof ApiAuthPasskeySignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/registration-options': {
      id: '/api/auth/passkey/registration-options'
      path: '/api/auth/passkey/registration-options'
      fullPath: '/api/auth/passkey/registration-options'
      preLoaderRoute: typeof ApiAuthPasskeyRegistrationOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/add-passkey': {
      id: '/api/auth/passkey/add-passkey'
      path: '/api/auth/passkey/add-passkey'
      fullPath: '/api/auth/passkey/add-passkey'
      preLoaderRoute: typeof ApiAuthPasskeyAddPasskeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/admin/products/new': {
      id: '/(authenticated)/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof authenticatedAdminProductsNewRouteImport
      parentRoute: typeof authenticatedAdminProductsRouteRoute
    }
    '/(authenticated)/admin/products/$productId': {
      id: '/(authenticated)/admin/products/$productId'
      path: '/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof authenticatedAdminProductsProductIdRouteImport
      parentRoute: typeof authenticatedAdminProductsRouteRoute
    }
    '/(authenticated)/admin/orders/$orderId': {
      id: '/(authenticated)/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof authenticatedAdminOrdersOrderIdRouteImport
      parentRoute: typeof authenticatedAdminOrdersRouteRoute
    }
    '/(authenticated)/admin/billing/subscriptions': {
      id: '/(authenticated)/admin/billing/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/billing/subscriptions'
      preLoaderRoute: typeof authenticatedAdminBillingSubscriptionsRouteImport
      parentRoute: typeof authenticatedAdminBillingRouteRoute
    }
    '/(authenticated)/admin/billing/customers': {
      id: '/(authenticated)/admin/billing/customers'
      path: '/customers'
      fullPath: '/admin/billing/customers'
      preLoaderRoute: typeof authenticatedAdminBillingCustomersRouteImport
      parentRoute: typeof authenticatedAdminBillingRouteRoute
    }
    '/(authenticated)/admin/billing/credits': {
      id: '/(authenticated)/admin/billing/credits'
      path: '/credits'
      fullPath: '/admin/billing/credits'
      preLoaderRoute: typeof authenticatedAdminBillingCreditsRouteImport
      parentRoute: typeof authenticatedAdminBillingRouteRoute
    }
    '/(auth-pages)/auth/callback/verify-email': {
      id: '/(auth-pages)/auth/callback/verify-email'
      path: '/auth/callback/verify-email'
      fullPath: '/auth/callback/verify-email'
      preLoaderRoute: typeof authPagesAuthCallbackVerifyEmailRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesLogoutRoute: typeof authPagesLogoutRoute
  authPagesSignupRoute: typeof authPagesSignupRoute
  authPagesAuthAuthViewRoute: typeof authPagesAuthAuthViewRoute
  authPagesAuthIndexRoute: typeof authPagesAuthIndexRoute
  authPagesAuthCallbackVerifyEmailRoute: typeof authPagesAuthCallbackVerifyEmailRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesLogoutRoute: authPagesLogoutRoute,
  authPagesSignupRoute: authPagesSignupRoute,
  authPagesAuthAuthViewRoute: authPagesAuthAuthViewRoute,
  authPagesAuthIndexRoute: authPagesAuthIndexRoute,
  authPagesAuthCallbackVerifyEmailRoute: authPagesAuthCallbackVerifyEmailRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedAccountRouteRouteChildren {
  authenticatedAccountAccountViewRoute: typeof authenticatedAccountAccountViewRoute
  authenticatedAccountIndexRoute: typeof authenticatedAccountIndexRoute
}

const authenticatedAccountRouteRouteChildren: authenticatedAccountRouteRouteChildren =
  {
    authenticatedAccountAccountViewRoute: authenticatedAccountAccountViewRoute,
    authenticatedAccountIndexRoute: authenticatedAccountIndexRoute,
  }

const authenticatedAccountRouteRouteWithChildren =
  authenticatedAccountRouteRoute._addFileChildren(
    authenticatedAccountRouteRouteChildren,
  )

interface authenticatedAdminBillingRouteRouteChildren {
  authenticatedAdminBillingCreditsRoute: typeof authenticatedAdminBillingCreditsRoute
  authenticatedAdminBillingCustomersRoute: typeof authenticatedAdminBillingCustomersRoute
  authenticatedAdminBillingSubscriptionsRoute: typeof authenticatedAdminBillingSubscriptionsRoute
  authenticatedAdminBillingIndexRoute: typeof authenticatedAdminBillingIndexRoute
}

const authenticatedAdminBillingRouteRouteChildren: authenticatedAdminBillingRouteRouteChildren =
  {
    authenticatedAdminBillingCreditsRoute:
      authenticatedAdminBillingCreditsRoute,
    authenticatedAdminBillingCustomersRoute:
      authenticatedAdminBillingCustomersRoute,
    authenticatedAdminBillingSubscriptionsRoute:
      authenticatedAdminBillingSubscriptionsRoute,
    authenticatedAdminBillingIndexRoute: authenticatedAdminBillingIndexRoute,
  }

const authenticatedAdminBillingRouteRouteWithChildren =
  authenticatedAdminBillingRouteRoute._addFileChildren(
    authenticatedAdminBillingRouteRouteChildren,
  )

interface authenticatedAdminOrdersRouteRouteChildren {
  authenticatedAdminOrdersOrderIdRoute: typeof authenticatedAdminOrdersOrderIdRoute
  authenticatedAdminOrdersIndexRoute: typeof authenticatedAdminOrdersIndexRoute
}

const authenticatedAdminOrdersRouteRouteChildren: authenticatedAdminOrdersRouteRouteChildren =
  {
    authenticatedAdminOrdersOrderIdRoute: authenticatedAdminOrdersOrderIdRoute,
    authenticatedAdminOrdersIndexRoute: authenticatedAdminOrdersIndexRoute,
  }

const authenticatedAdminOrdersRouteRouteWithChildren =
  authenticatedAdminOrdersRouteRoute._addFileChildren(
    authenticatedAdminOrdersRouteRouteChildren,
  )

interface authenticatedAdminProductsRouteRouteChildren {
  authenticatedAdminProductsProductIdRoute: typeof authenticatedAdminProductsProductIdRoute
  authenticatedAdminProductsNewRoute: typeof authenticatedAdminProductsNewRoute
  authenticatedAdminProductsIndexRoute: typeof authenticatedAdminProductsIndexRoute
}

const authenticatedAdminProductsRouteRouteChildren: authenticatedAdminProductsRouteRouteChildren =
  {
    authenticatedAdminProductsProductIdRoute:
      authenticatedAdminProductsProductIdRoute,
    authenticatedAdminProductsNewRoute: authenticatedAdminProductsNewRoute,
    authenticatedAdminProductsIndexRoute: authenticatedAdminProductsIndexRoute,
  }

const authenticatedAdminProductsRouteRouteWithChildren =
  authenticatedAdminProductsRouteRoute._addFileChildren(
    authenticatedAdminProductsRouteRouteChildren,
  )

interface authenticatedAdminRouteRouteChildren {
  authenticatedAdminBillingRouteRoute: typeof authenticatedAdminBillingRouteRouteWithChildren
  authenticatedAdminOrdersRouteRoute: typeof authenticatedAdminOrdersRouteRouteWithChildren
  authenticatedAdminProductsRouteRoute: typeof authenticatedAdminProductsRouteRouteWithChildren
  authenticatedAdminCouponsRoute: typeof authenticatedAdminCouponsRoute
  authenticatedAdminCustomersRoute: typeof authenticatedAdminCustomersRoute
  authenticatedAdminInventoryRoute: typeof authenticatedAdminInventoryRoute
  authenticatedAdminRbacRoute: typeof authenticatedAdminRbacRoute
  authenticatedAdminReviewsRoute: typeof authenticatedAdminReviewsRoute
  authenticatedAdminShippingRoute: typeof authenticatedAdminShippingRoute
  authenticatedAdminStorageRoute: typeof authenticatedAdminStorageRoute
  authenticatedAdminUsersRoute: typeof authenticatedAdminUsersRoute
  authenticatedAdminIndexRoute: typeof authenticatedAdminIndexRoute
}

const authenticatedAdminRouteRouteChildren: authenticatedAdminRouteRouteChildren =
  {
    authenticatedAdminBillingRouteRoute:
      authenticatedAdminBillingRouteRouteWithChildren,
    authenticatedAdminOrdersRouteRoute:
      authenticatedAdminOrdersRouteRouteWithChildren,
    authenticatedAdminProductsRouteRoute:
      authenticatedAdminProductsRouteRouteWithChildren,
    authenticatedAdminCouponsRoute: authenticatedAdminCouponsRoute,
    authenticatedAdminCustomersRoute: authenticatedAdminCustomersRoute,
    authenticatedAdminInventoryRoute: authenticatedAdminInventoryRoute,
    authenticatedAdminRbacRoute: authenticatedAdminRbacRoute,
    authenticatedAdminReviewsRoute: authenticatedAdminReviewsRoute,
    authenticatedAdminShippingRoute: authenticatedAdminShippingRoute,
    authenticatedAdminStorageRoute: authenticatedAdminStorageRoute,
    authenticatedAdminUsersRoute: authenticatedAdminUsersRoute,
    authenticatedAdminIndexRoute: authenticatedAdminIndexRoute,
  }

const authenticatedAdminRouteRouteWithChildren =
  authenticatedAdminRouteRoute._addFileChildren(
    authenticatedAdminRouteRouteChildren,
  )

interface authenticatedBillingRouteRouteChildren {
  authenticatedBillingCancelRoute: typeof authenticatedBillingCancelRoute
  authenticatedBillingSuccessRoute: typeof authenticatedBillingSuccessRoute
  authenticatedBillingIndexRoute: typeof authenticatedBillingIndexRoute
}

const authenticatedBillingRouteRouteChildren: authenticatedBillingRouteRouteChildren =
  {
    authenticatedBillingCancelRoute: authenticatedBillingCancelRoute,
    authenticatedBillingSuccessRoute: authenticatedBillingSuccessRoute,
    authenticatedBillingIndexRoute: authenticatedBillingIndexRoute,
  }

const authenticatedBillingRouteRouteWithChildren =
  authenticatedBillingRouteRoute._addFileChildren(
    authenticatedBillingRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedAccountRouteRoute: typeof authenticatedAccountRouteRouteWithChildren
  authenticatedAdminRouteRoute: typeof authenticatedAdminRouteRouteWithChildren
  authenticatedBillingRouteRoute: typeof authenticatedBillingRouteRouteWithChildren
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRoute
  authenticatedErrorsErrorRoute: typeof authenticatedErrorsErrorRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedAccountRouteRoute: authenticatedAccountRouteRouteWithChildren,
  authenticatedAdminRouteRoute: authenticatedAdminRouteRouteWithChildren,
  authenticatedBillingRouteRoute: authenticatedBillingRouteRouteWithChildren,
  authenticatedDashboardRouteRoute: authenticatedDashboardRouteRoute,
  authenticatedErrorsErrorRoute: authenticatedErrorsErrorRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  CookiesRouteRoute: CookiesRouteRoute,
  PrivacyRouteRoute: PrivacyRouteRoute,
  TermsRouteRoute: TermsRouteRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInngestInngestRoute: ApiInngestInngestRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiAuthPasskeyAddPasskeyRoute: ApiAuthPasskeyAddPasskeyRoute,
  ApiAuthPasskeyRegistrationOptionsRoute:
    ApiAuthPasskeyRegistrationOptionsRoute,
  ApiAuthPasskeySignInRoute: ApiAuthPasskeySignInRoute,
  ApiAuthPasskeyVerifyRegistrationRoute: ApiAuthPasskeyVerifyRegistrationRoute,
  ApiStorageAvatarUserIdRoute: ApiStorageAvatarUserIdRoute,
  ApiStorageFilesSplatRoute: ApiStorageFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
